// English -> Urdu interface strings, used by the DOM translator in i18n.jsx.
// Keys are the English text exactly as rendered (whitespace collapsed).
export const UR = {
  "My account": "میرا اکاؤنٹ",
  "Changing it signs you out on every other device.": "اسے تبدیل کرنے سے آپ باقی تمام آلات پر سائن آؤٹ ہو جائیں گے۔",
  "Current password": "موجودہ پاس ورڈ",
  "Payments": "ادائیگیاں",
  "Platform revenue": "پلیٹ فارم کی آمدنی",
  "Online fees processed": "آن لائن فیسیں",
  "Commission earned": "کمیشن",
  "Outstanding invoices": "واجب الادا انوائسز",
  "Collected": "وصول شدہ",
  "Refunded fees": "واپس کی گئی فیسیں",
  "Create invoice": "انوائس بنائیں",
  "Invoices": "انوائسز",
  "Mark paid": "ادا شدہ کریں",
  "Reopen": "دوبارہ کھولیں",
  "Platform fee invoices": "پلیٹ فارم فیس کی انوائسز",
  "Platform fee": "پلیٹ فارم فیس",
  "Online fees": "آن لائن فیسیں",
  "Any status": "کوئی بھی حیثیت",
  "Online payments": "آن لائن ادائیگیاں",
  "Pay online": "آن لائن ادائیگی کریں",
  "Mark refunded": "رقم واپس کر دی",
  "Refund due": "رقم واپسی باقی",
  "Refunded": "رقم واپس",
  "Update keys": "کلیدیں اپ ڈیٹ کریں",
  "Disconnect": "منقطع کریں",
  "Connect Safepay": "سیف پے منسلک کریں",
  "Save keys": "کلیدیں محفوظ کریں",
  "Public key": "پبلک کلید",
  "Secret key": "خفیہ کلید",
  "Webhook secret (optional)": "ویب ہک خفیہ کلید (اختیاری)",
  "Mode": "موڈ",
  "Sandbox (test)": "سینڈ باکس (ٹیسٹ)",
  "Live": "لائیو",
  "Payment updates": "ادائیگی کی اطلاعات",
  "Checked": "جانچا گیا",
  "Webhook address for Safepay": "سیف پے کے لیے ویب ہک ایڈریس",
  "Payment cancelled": "ادائیگی منسوخ",
  "Confirming your payment…": "آپ کی ادائیگی کی تصدیق ہو رہی ہے…",
  "Refund on its way": "رقم کی واپسی جاری ہے",
  "Disconnect Safepay?": "سیف پے منقطع کریں؟",
  "I have refunded it": "میں نے رقم واپس کر دی",
  "Stored encrypted. Never shown again.": "محفوظ (انکرپٹڈ) طریقے سے رکھی جاتی ہے۔ دوبارہ نہیں دکھائی جاتی۔",
  "We check the keys with Safepay before saving. In sandbox mode no real money moves.": "محفوظ کرنے سے پہلے ہم سیف پے سے کلیدیں جانچتے ہیں۔ سینڈ باکس موڈ میں کوئی اصل رقم منتقل نہیں ہوتی۔",
  "Language & theme": "زبان اور تھیم",
  "A 30-minute brisk walk five days a week cuts heart-disease risk significantly.": "ہفتے میں پانچ دن 30 منٹ کی تیز چہل قدمی دل کی بیماری کا خطرہ نمایاں طور پر کم کرتی ہے۔",
  "A read-only link to your history for a one-off visit or a second opinion. No account needed, and it expires on its own.": "ایک بار کے معائنے یا دوسری رائے کے لیے آپ کی ہسٹری کا صرف دیکھنے والا لنک۔ اکاؤنٹ کی ضرورت نہیں، اور یہ خود بخود ختم ہو جاتا ہے۔",
  "AI assistant": "اے آئی اسسٹنٹ",
  "AI brief": "اے آئی خلاصہ",
  "AI filled": "اے آئی نے بھرا",
  "AI suggestions can be wrong. Discuss them with your doctor.": "اے آئی کی تجاویز غلط ہو سکتی ہیں۔ ان پر اپنے ڈاکٹر سے بات کریں۔",
  "API key created": "اے پی آئی کلید بن گئی",
  "Accept": "قبول کریں",
  "Access control": "رسائی کا کنٹرول",
  "Account": "اکاؤنٹ",
  "Account created. Sign in to continue.": "اکاؤنٹ بن گیا۔ جاری رکھنے کے لیے سائن اِن کریں۔",
  "Account restored": "اکاؤنٹ بحال ہو گیا",
  "Account suspended": "اکاؤنٹ معطل ہو گیا",
  "Accounts": "اکاؤنٹس",
  "Actions": "کارروائیاں",
  "Active": "فعال",
  "Add": "شامل کریں",
  "Add a child with their B-Form number, or an elderly parent with their CNIC.": "بچے کو اس کے ب فارم نمبر سے، یا بزرگ والدین کو ان کے شناختی کارڈ سے شامل کریں۔",
  "Add a date of birth": "تاریخ پیدائش شامل کریں",
  "Add a doctor first": "پہلے ڈاکٹر شامل کریں",
  "Add a family member": "خاندان کا فرد شامل کریں",
  "Add a past report, prescription or test result. Your doctor verifies it before it joins your history.": "پرانی رپورٹ، نسخہ یا ٹیسٹ کا نتیجہ شامل کریں۔ آپ کی ہسٹری میں شامل ہونے سے پہلے آپ کا ڈاکٹر اس کی تصدیق کرتا ہے۔",
  "Add a photo or PDF. AI reads it and fills in the details.": "تصویر یا پی ڈی ایف شامل کریں۔ اے آئی اسے پڑھ کر تفصیلات بھر دیتا ہے۔",
  "Add a time": "وقت شامل کریں",
  "Add doctors": "ڈاکٹر شامل کریں",
  "Add doctors to your care team. Only the doctors you add can see your records.": "اپنی کیئر ٹیم میں ڈاکٹر شامل کریں۔ صرف آپ کے شامل کردہ ڈاکٹر ہی آپ کا ریکارڈ دیکھ سکتے ہیں۔",
  "Add evening block": "شام کا وقت شامل کریں",
  "Add family member": "خاندان کا فرد شامل کریں",
  "Add front-desk staff": "استقبالیہ عملہ شامل کریں",
  "Add medication": "دوا شامل کریں",
  "Add medicine": "دوا شامل کریں",
  "Add or remove medicines": "دوائیں شامل کریں یا ہٹائیں",
  "Add record": "ریکارڈ شامل کریں",
  "Add the date of birth in the health profile to see the vaccination schedule.": "ویکسینیشن شیڈول دیکھنے کے لیے ہیلتھ پروفائل میں تاریخ پیدائش شامل کریں۔",
  "Add the doctors who treat you so they can see your history and you can book with them.": "اپنا علاج کرنے والے ڈاکٹروں کو شامل کریں تاکہ وہ آپ کی ہسٹری دیکھ سکیں اور آپ ان سے وقت لے سکیں۔",
  "Add the first record": "پہلا ریکارڈ شامل کریں",
  "Add to care team": "کیئر ٹیم میں شامل کریں",
  "Add to care team & book": "کیئر ٹیم میں شامل کریں اور وقت لیں",
  "Add vaccination": "ویکسین شامل کریں",
  "Add your blood group and an emergency contact in your health profile so the card is useful.": "کارڈ کو کارآمد بنانے کے لیے ہیلتھ پروفائل میں اپنا بلڈ گروپ اور ہنگامی رابطہ شامل کریں۔",
  "Add your medicines in your health profile, or they appear here when a doctor prescribes them.": "اپنی دوائیں ہیلتھ پروفائل میں شامل کریں، یا ڈاکٹر کے نسخہ لکھنے پر وہ یہاں نظر آئیں گی۔",
  "Add your phone number in Profile first": "پہلے پروفائل میں اپنا فون نمبر شامل کریں",
  "Added directly to the patient": "براہ راست مریض کے ریکارڈ میں شامل",
  "Added to history": "ہسٹری میں شامل",
  "Address": "پتہ",
  "Adherence": "دوا کی پابندی",
  "Adherence (30 days)": "دوا کی پابندی (30 دن)",
  "Admin": "ایڈمن",
  "Adults need 7–9 hours of sleep. Keep screens out of bed for better rest.": "بالغوں کو 7 سے 9 گھنٹے نیند چاہیے۔ بہتر آرام کے لیے بستر پر اسکرین سے دور رہیں۔",
  "Affiliated hospital": "منسلک ہسپتال",
  "All": "سب",
  "All caught up": "سب مکمل",
  "All cities": "تمام شہر",
  "All doctors": "تمام ڈاکٹر",
  "All notes": "تمام نوٹس",
  "All of their records, documents and appointments will be permanently deleted.": "ان کے تمام ریکارڈ، دستاویزات اور اپوائنٹمنٹس ہمیشہ کے لیے حذف ہو جائیں گی۔",
  "All patients": "تمام مریض",
  "All specialties": "تمام شعبے",
  "All taken": "سب لی گئیں",
  "All your verified records and their documents are included.": "آپ کے تمام تصدیق شدہ ریکارڈ اور ان کی دستاویزات شامل ہیں۔",
  "Allergies": "الرجی",
  "Allergies:": "الرجی:",
  "Allergy": "الرجی",
  "Almost done": "تقریباً مکمل",
  "Already booked": "پہلے سے بُک",
  "Already have an account?": "پہلے سے اکاؤنٹ ہے؟",
  "Amount": "رقم",
  "Amount received (Rs)": "وصول شدہ رقم (روپے)",
  "Amount received at the clinic (Rs)": "کلینک پر وصول شدہ رقم (روپے)",
  "Analytics": "تجزیات",
  "Anyone with the link can view, so share it only with the doctor.": "لنک رکھنے والا کوئی بھی اسے دیکھ سکتا ہے، اس لیے صرف ڈاکٹر کے ساتھ شیئر کریں۔",
  "Appointment": "اپوائنٹمنٹ",
  "Appointment booked": "اپوائنٹمنٹ بُک ہو گئی",
  "Appointment booked. The patient was notified.": "اپوائنٹمنٹ بُک ہو گئی۔ مریض کو اطلاع دے دی گئی۔",
  "Appointment cancelled. The patient has been notified.": "اپوائنٹمنٹ منسوخ ہو گئی۔ مریض کو اطلاع دے دی گئی ہے۔",
  "Appointment cancelled. Your doctor has been notified.": "اپوائنٹمنٹ منسوخ ہو گئی۔ آپ کے ڈاکٹر کو اطلاع دے دی گئی ہے۔",
  "Appointment insights": "اپوائنٹمنٹ کا تجزیہ",
  "Appointment length": "اپوائنٹمنٹ کا دورانیہ",
  "Appointment reminders": "اپوائنٹمنٹ کی یاد دہانیاں",
  "Appointments": "اپوائنٹمنٹس",
  "Appointments by hour": "گھنٹے کے لحاظ سے اپوائنٹمنٹس",
  "Appointments by weekday": "دن کے لحاظ سے اپوائنٹمنٹس",
  "Appointments per day": "روزانہ اپوائنٹمنٹس",
  "Approve": "منظور کریں",
  "Approved": "منظور",
  "Approved and added to patient history": "منظور ہو کر مریض کی ہسٹری میں شامل",
  "As needed": "ضرورت کے مطابق",
  "Ask AI": "اے آئی سے پوچھیں",
  "Ask anything… (Urdu or English)": "کچھ بھی پوچھیں… (اردو یا انگریزی)",
  "Ask for a code from an authenticator app (Google Authenticator, Microsoft Authenticator…) after your password.": "پاس ورڈ کے بعد تصدیقی ایپ (گوگل آتھینٹیکیٹر، مائیکروسافٹ آتھینٹیکیٹر…) سے کوڈ مانگیں۔",
  "Ask in English or Urdu. It reads your records, explains results and can book visits for you.": "انگریزی یا اردو میں پوچھیں۔ یہ آپ کا ریکارڈ پڑھتا ہے، نتائج سمجھاتا ہے اور آپ کے لیے وقت بُک کر سکتا ہے۔",
  "Ask me about your health record": "اپنے ہیلتھ ریکارڈ کے بارے میں مجھ سے پوچھیں",
  "Ask the AI assistant": "اے آئی اسسٹنٹ سے پوچھیں",
  "Assistant not configured": "اسسٹنٹ ترتیب نہیں دیا گیا",
  "Assistant unavailable": "اسسٹنٹ دستیاب نہیں",
  "Asthma": "دمہ",
  "At bedtime": "سوتے وقت",
  "At least 8 characters": "کم از کم 8 حروف",
  "At least 8 characters. Ask them to change it after signing in.": "کم از کم 8 حروف۔ سائن اِن کے بعد انہیں اسے تبدیل کرنے کا کہیں۔",
  "Attach reports or scans (optional)": "رپورٹس یا اسکین منسلک کریں (اختیاری)",
  "Authenticator QR code": "تصدیقی کیو آر کوڈ",
  "Awaiting review": "جائزے کا منتظر",
  "B-Form or CNIC number": "ب فارم یا شناختی کارڈ نمبر",
  "Back to appointments": "اپوائنٹمنٹس پر واپس",
  "Back to directory": "ڈائریکٹری پر واپس",
  "Back to my appointments": "میری اپوائنٹمنٹس پر واپس",
  "Back to sign in": "سائن اِن پر واپس",
  "Back to today": "آج پر واپس",
  "Backup link": "متبادل لنک",
  "Based on Pakistan's Expanded Programme on Immunization routine schedule. Your doctor may advise a different timing; polio campaign drops are given in addition.": "پاکستان کے توسیعی پروگرام برائے حفاظتی ٹیکہ جات (ای پی آئی) کے معمول کے شیڈول پر مبنی۔ آپ کا ڈاکٹر مختلف وقت تجویز کر سکتا ہے؛ پولیو مہم کے قطرے اس کے علاوہ ہیں۔",
  "Bio": "تعارف",
  "Blood glucose": "بلڈ شوگر",
  "Blood group": "بلڈ گروپ",
  "Blood pressure": "بلڈ پریشر",
  "Book": "بُک کریں",
  "Book a follow-up with my doctor next week": "اگلے ہفتے میرے ڈاکٹر کے ساتھ فالو اپ بُک کریں",
  "Book a visit": "وقت لیں",
  "Book a visit with a doctor from your care team.": "اپنی کیئر ٹیم کے کسی ڈاکٹر سے وقت لیں۔",
  "Book a yearly check-up even when you feel fine. Prevention beats cure.": "طبیعت ٹھیک ہو تب بھی سالانہ چیک اپ کروائیں۔ احتیاط علاج سے بہتر ہے۔",
  "Book an appointment": "اپوائنٹمنٹ بُک کریں",
  "Book another": "ایک اور بُک کریں",
  "Book appointment": "اپوائنٹمنٹ بُک کریں",
  "Book one now": "ابھی بُک کریں",
  "Book with your care team": "اپنی کیئر ٹیم سے وقت لیں",
  "Booked": "بُک شدہ",
  "Brief me on my next patient": "میرے اگلے مریض کا خلاصہ بتائیں",
  "Bring your clinic's doctors together with a shared front desk, one schedule and clinic-wide analytics.": "اپنے کلینک کے ڈاکٹروں کو مشترکہ استقبالیہ، ایک شیڈول اور پورے کلینک کے تجزیے کے ساتھ اکٹھا کریں۔",
  "Build your care team": "اپنی کیئر ٹیم بنائیں",
  "Built for patients.": "مریضوں کے لیے بنایا گیا۔",
  "Busiest day": "مصروف ترین دن",
  "Busiest days": "مصروف ترین دن",
  "Busiest hours": "مصروف ترین اوقات",
  "By time of day": "دن کے وقت کے لحاظ سے",
  "CNIC": "شناختی کارڈ",
  "CNIC must be 13 digits": "شناختی کارڈ نمبر 13 ہندسوں کا ہونا چاہیے",
  "CNIC or email": "شناختی کارڈ یا ای میل",
  "Camera and microphone are blocked. Allow them in your browser settings.": "کیمرہ اور مائیکروفون بند ہیں۔ براؤزر کی سیٹنگز میں انہیں اجازت دیں۔",
  "Can't find it? Check your spam folder, or try again with your email address.": "نہیں ملی؟ اسپام فولڈر دیکھیں، یا اپنے ای میل ایڈریس سے دوبارہ کوشش کریں۔",
  "Can't find it? Check your spam folder.": "نہیں ملی؟ اپنا اسپام فولڈر دیکھیں۔",
  "Can't scan? Enter this key manually:": "اسکین نہیں ہو رہا؟ یہ کلید خود درج کریں:",
  "Cancel": "منسوخ کریں",
  "Cancel appointment": "اپوائنٹمنٹ منسوخ کریں",
  "Cancel appointment?": "اپوائنٹمنٹ منسوخ کریں؟",
  "Cancel payment": "ادائیگی منسوخ کریں",
  "Cancel prescription": "نسخہ منسوخ کریں",
  "Cancel this appointment?": "یہ اپوائنٹمنٹ منسوخ کریں؟",
  "Cancel this prescription?": "یہ نسخہ منسوخ کریں؟",
  "Cancellation rate": "منسوخی کی شرح",
  "Cancelled": "منسوخ",
  "Cancelled by the doctor": "ڈاکٹر نے منسوخ کیا",
  "Cancer": "کینسر",
  "Card not active": "کارڈ فعال نہیں",
  "Cardiology": "امراضِ قلب",
  "Care": "علاج",
  "Care team": "کیئر ٹیم",
  "Carry your history": "اپنی ہسٹری ساتھ رکھیں",
  "Category": "زمرہ",
  "Change password": "پاس ورڈ تبدیل کریں",
  "Charts": "چارٹس",
  "Check again": "دوبارہ جانچیں",
  "Check in": "حاضری لگائیں",
  "Check safety": "حفاظت جانچیں",
  "Check that the name and registration number match the PMDC register at": "تصدیق کریں کہ نام اور رجسٹریشن نمبر پی ایم ڈی سی رجسٹر سے ملتے ہیں:",
  "Check the details": "تفصیلات جانچیں",
  "Check your email": "اپنی ای میل دیکھیں",
  "Check your inbox": "اپنا ان باکس دیکھیں",
  "Checked in": "حاضر",
  "Checking allergies and interactions…": "الرجی اور دواؤں کے باہمی اثرات جانچے جا رہے ہیں…",
  "Checks support your judgement; they are not exhaustive.": "یہ جانچ آپ کے فیصلے میں مدد کے لیے ہے؛ یہ مکمل نہیں۔",
  "Childhood schedule complete": "بچپن کا شیڈول مکمل",
  "Children: the 13-digit number on their NADRA B-Form": "بچے: نادرا ب فارم پر درج 13 ہندسوں کا نمبر",
  "Choose a doctor": "ڈاکٹر منتخب کریں",
  "Choose a doctor from your care team": "اپنی کیئر ٹیم سے ڈاکٹر منتخب کریں",
  "Choose a doctor from your care team, pick a day and a time slot.": "اپنی کیئر ٹیم سے ڈاکٹر، دن اور وقت منتخب کریں۔",
  "Choose a new password": "نیا پاس ورڈ منتخب کریں",
  "Choose files": "فائلیں منتخب کریں",
  "Chronic conditions": "دائمی امراض",
  "City": "شہر",
  "Clear": "صاف کریں",
  "Clinic": "کلینک",
  "Clinic address": "کلینک کا پتہ",
  "Clinic created": "کلینک بن گیا",
  "Clinic front desk": "کلینک استقبالیہ",
  "Clinic front desk?": "کلینک استقبالیہ؟",
  "Clinic hours": "کلینک کے اوقات",
  "Clinic hours saved. Patients now see these slots.": "کلینک کے اوقات محفوظ ہو گئے۔ اب مریضوں کو یہی اوقات نظر آئیں گے۔",
  "Clinic insights": "کلینک کا تجزیہ",
  "Clinic invitation": "کلینک کا دعوت نامہ",
  "Clinic name": "کلینک کا نام",
  "Clinic performance": "کلینک کی کارکردگی",
  "Clinical co-pilot": "طبی معاون",
  "Clinical notes": "طبی نوٹس",
  "Clinics": "کلینکس",
  "Close": "بند کریں",
  "Close assistant": "اسسٹنٹ بند کریں",
  "Close brief": "خلاصہ بند کریں",
  "Close menu": "مینو بند کریں",
  "Closed": "بند",
  "Code": "کوڈ",
  "Codes copied": "کوڈز کاپی ہو گئے",
  "Coming soon": "جلد آ رہا ہے",
  "Complete": "مکمل کریں",
  "Complete patient timelines": "مریضوں کی مکمل ٹائم لائن",
  "Complete your health profile": "اپنا ہیلتھ پروفائل مکمل کریں",
  "Completed": "مکمل",
  "Completed and cancelled appointments will appear here.": "مکمل اور منسوخ شدہ اپوائنٹمنٹس یہاں نظر آئیں گی۔",
  "Completed visits": "مکمل معائنے",
  "Completion rate": "تکمیل کی شرح",
  "Conditions": "امراض",
  "Conditions in parents, siblings or grandparents.": "والدین، بہن بھائیوں یا دادا دادی/نانا نانی کی بیماریاں۔",
  "Confirm": "تصدیق کریں",
  "Confirm booking": "بُکنگ کی تصدیق کریں",
  "Confirm new password": "نئے پاس ورڈ کی تصدیق کریں",
  "Confirm password": "پاس ورڈ کی تصدیق کریں",
  "Connecting…": "جڑ رہا ہے…",
  "Connection lost.": "رابطہ منقطع ہو گیا۔",
  "Connection lost. Please try again.": "رابطہ منقطع ہو گیا۔ دوبارہ کوشش کریں۔",
  "Consider downloading your data first.": "بہتر ہے پہلے اپنا ڈیٹا ڈاؤن لوڈ کر لیں۔",
  "Consultation fee (Rs)": "مشاورتی فیس (روپے)",
  "Consultation notes": "معائنے کے نوٹس",
  "Continue with Google": "گوگل کے ساتھ جاری رکھیں",
  "Control how you sign in, who can see your information and what we send you.": "طے کریں کہ آپ کیسے سائن اِن کرتے ہیں، آپ کی معلومات کون دیکھ سکتا ہے اور ہم آپ کو کیا بھیجتے ہیں۔",
  "Conversations": "گفتگو",
  "Copy": "کاپی کریں",
  "Copy codes": "کوڈز کاپی کریں",
  "Copy it now: for security it won't be shown again.": "ابھی کاپی کر لیں: حفاظت کے لیے یہ دوبارہ نہیں دکھائی جائے گی۔",
  "Copy key": "کلید کاپی کریں",
  "Copy link": "لنک کاپی کریں",
  "Could not copy": "کاپی نہیں ہو سکا",
  "Could not create the PDF": "پی ڈی ایف نہیں بن سکی",
  "Could not create your account": "آپ کا اکاؤنٹ نہیں بن سکا",
  "Could not load the document": "دستاویز لوڈ نہیں ہو سکی",
  "Could not load the file.": "فائل لوڈ نہیں ہو سکی۔",
  "Could not reach the server": "سرور سے رابطہ نہیں ہو سکا",
  "Could not read this file": "یہ فائل پڑھی نہیں جا سکی",
  "Could not reset the password": "پاس ورڈ ری سیٹ نہیں ہو سکا",
  "Course ends": "کورس ختم",
  "Create account": "اکاؤنٹ بنائیں",
  "Create an account": "اکاؤنٹ بنائیں",
  "Create clinic": "کلینک بنائیں",
  "Create link": "لنک بنائیں",
  "Create login": "لاگ اِن بنائیں",
  "Create one before your next visit and show the QR code to the doctor.": "اگلے معائنے سے پہلے ایک بنائیں اور ڈاکٹر کو کیو آر کوڈ دکھائیں۔",
  "Create patient account": "مریض کا اکاؤنٹ بنائیں",
  "Create your account": "اپنا اکاؤنٹ بنائیں",
  "Current medications": "موجودہ دوائیں",
  "Current medicines": "موجودہ دوائیں",
  "Current profile": "موجودہ پروفائل",
  "Daily health tip": "روزانہ صحت کا مشورہ",
  "Dark theme": "ڈارک تھیم",
  "Database size (MB)": "ڈیٹا بیس کا سائز (ایم بی)",
  "Date": "تاریخ",
  "Date given": "لگنے کی تاریخ",
  "Date of birth": "تاریخ پیدائش",
  "Daughter": "بیٹی",
  "Day": "دن",
  "Day off": "چھٹی",
  "Days": "دن",
  "Days off": "چھٹیاں",
  "Decline": "مسترد کریں",
  "Delete": "حذف کریں",
  "Delete account": "اکاؤنٹ حذف کریں",
  "Delete conversation": "گفتگو حذف کریں",
  "Delete note": "نوٹ حذف کریں",
  "Delete permanently": "ہمیشہ کے لیے حذف کریں",
  "Delete profile": "پروفائل حذف کریں",
  "Delete reading": "ریڈنگ حذف کریں",
  "Delete record": "ریکارڈ حذف کریں",
  "Delete this note?": "یہ نوٹ حذف کریں؟",
  "Delete this reading?": "یہ ریڈنگ حذف کریں؟",
  "Delete this record?": "یہ ریکارڈ حذف کریں؟",
  "Delete your account?": "اپنا اکاؤنٹ حذف کریں؟",
  "Dentistry": "دندان سازی",
  "Dermatology": "امراضِ جلد",
  "Describe the record, or upload a file above.": "ریکارڈ کی تفصیل لکھیں، یا اوپر فائل اپ لوڈ کریں۔",
  "Developers": "ڈیولپرز",
  "Diabetes": "ذیابیطس",
  "Diagnosis": "تشخیص",
  "Diagnosis, findings, prescriptions, follow-up…": "تشخیص، معائنے کے نتائج، نسخے، فالو اپ…",
  "Diastolic": "نچلا",
  "Directory": "ڈائریکٹری",
  "Directory listing": "ڈائریکٹری میں اندراج",
  "Disable": "غیر فعال کریں",
  "Disabled": "غیر فعال",
  "Discard": "رد کریں",
  "Dismiss": "نظر انداز کریں",
  "Dispensed": "دوا دے دی گئی",
  "Do any of my patients have abnormal vitals?": "کیا میرے کسی مریض کے وائٹلز غیر معمولی ہیں؟",
  "Doctor": "ڈاکٹر",
  "Doctor CNIC to invite": "مدعو کرنے کے لیے ڈاکٹر کا شناختی کارڈ",
  "Doctor directory": "ڈاکٹروں کی ڈائریکٹری",
  "Doctor not available": "ڈاکٹر دستیاب نہیں",
  "Doctor not found": "ڈاکٹر نہیں ملا",
  "Doctor not verified": "ڈاکٹر کی تصدیق نہیں ہوئی",
  "Doctor rejected": "ڈاکٹر مسترد",
  "Doctor removed": "ڈاکٹر ہٹا دیا گیا",
  "Doctor reviews": "ڈاکٹر کا جائزہ",
  "Doctor sign in": "ڈاکٹر سائن اِن",
  "Doctor verification": "ڈاکٹر کی تصدیق",
  "Doctor verification, reports and partners.": "ڈاکٹروں کی تصدیق، رپورٹس اور شراکت دار۔",
  "Doctor verified": "ڈاکٹر کی تصدیق ہو گئی",
  "Doctor-gated access": "صرف ڈاکٹر کی رسائی",
  "Doctor-verified": "ڈاکٹر سے تصدیق شدہ",
  "Doctor-verified history": "ڈاکٹر سے تصدیق شدہ ہسٹری",
  "Doctors": "ڈاکٹر",
  "Doctors get live analytics on appointment load by weekday and time slot to plan their clinic.": "ڈاکٹروں کو کلینک کی منصوبہ بندی کے لیے دن اور وقت کے لحاظ سے اپوائنٹمنٹس کا براہ راست تجزیہ ملتا ہے۔",
  "Done": "مکمل",
  "Dose": "خوراک",
  "Dose (e.g. 500mg)": "خوراک (مثلاً 500mg)",
  "Dose (e.g. 5mg)": "خوراک (مثلاً 5mg)",
  "Download PDF": "پی ڈی ایف ڈاؤن لوڈ کریں",
  "Download a copy of everything, or close your account for good.": "ہر چیز کی کاپی ڈاؤن لوڈ کریں، یا اپنا اکاؤنٹ ہمیشہ کے لیے بند کریں۔",
  "Download any record as PDF": "کوئی بھی ریکارڈ پی ڈی ایف میں ڈاؤن لوڈ کریں",
  "Download failed": "ڈاؤن لوڈ ناکام",
  "Download my data": "میرا ڈیٹا ڈاؤن لوڈ کریں",
  "Download original": "اصل فائل ڈاؤن لوڈ کریں",
  "Download receipt": "رسید ڈاؤن لوڈ کریں",
  "Download wallet card": "بٹوے والا کارڈ ڈاؤن لوڈ کریں",
  "Dr.": "ڈاکٹر",
  "Drag files here or click to browse": "فائلیں یہاں کھینچیں یا منتخب کرنے کے لیے کلک کریں",
  "Drop to upload": "اپ لوڈ کے لیے چھوڑیں",
  "Due": "واجب",
  "Due now": "ابھی واجب",
  "Duration": "دورانیہ",
  "Duration in days": "دنوں میں دورانیہ",
  "E-prescription": "ای نسخہ",
  "E-prescriptions": "ای نسخے",
  "Eat a balanced plate: half vegetables, a quarter protein, a quarter whole grains.": "متوازن کھانا کھائیں: آدھی پلیٹ سبزیاں، چوتھائی پروٹین، چوتھائی ثابت اناج۔",
  "Edit": "ترمیم کریں",
  "Elevated": "قدرے زیادہ",
  "Email": "ای میل",
  "Email verified": "ای میل کی تصدیق ہو گئی",
  "Emergency QR card": "ہنگامی کیو آر کارڈ",
  "Emergency QR code": "ہنگامی کیو آر کوڈ",
  "Emergency QR on or off": "ہنگامی کیو آر آن یا آف",
  "Emergency card": "ہنگامی کارڈ",
  "Emergency contact": "ہنگامی رابطہ",
  "Emergency medical information": "ہنگامی طبی معلومات",
  "Enable": "فعال کریں",
  "Enabled": "فعال",
  "Encrypted passwords": "محفوظ پاس ورڈز",
  "Endocrinology": "غدودی امراض",
  "English": "English",
  "Enter a current code from your authenticator app to confirm.": "تصدیق کے لیے اپنی تصدیقی ایپ کا موجودہ کوڈ درج کریں۔",
  "Enter a valid email": "درست ای میل درج کریں",
  "Enter one of the recovery codes you saved when you turned on two-step sign-in.": "دو مرحلہ سائن اِن آن کرتے وقت محفوظ کیے گئے بحالی کوڈز میں سے ایک درج کریں۔",
  "Enter your CNIC or the email on your account and we'll send you a reset link.": "اپنا شناختی کارڈ نمبر یا اکاؤنٹ کی ای میل درج کریں، ہم آپ کو ری سیٹ لنک بھیج دیں گے۔",
  "Enter your password": "اپنا پاس ورڈ درج کریں",
  "Errors": "خرابیاں",
  "Every diagnosis, prescription and report in one timeline that follows you from Ziauddin to Aga Khan and beyond.": "ہر تشخیص، نسخہ اور رپورٹ ایک ٹائم لائن میں جو ضیاء الدین سے آغا خان اور اس سے آگے تک آپ کے ساتھ رہتی ہے۔",
  "Every doctor listed has had their PMDC registration checked by our team. Add a doctor to your care team to book and share your records with them.": "یہاں درج ہر ڈاکٹر کی پی ایم ڈی سی رجسٹریشن ہماری ٹیم نے جانچی ہے۔ وقت لینے اور ریکارڈ شیئر کرنے کے لیے ڈاکٹر کو اپنی کیئر ٹیم میں شامل کریں۔",
  "Every hospital keeps its own file.": "ہر ہسپتال اپنی الگ فائل رکھتا ہے۔",
  "Every hospital.": "ہر ہسپتال۔",
  "Every test result from your uploaded reports, side by side over time.": "آپ کی اپ لوڈ کردہ رپورٹس کا ہر ٹیسٹ نتیجہ، وقت کے ساتھ ساتھ۔",
  "Every time a doctor, share link, emergency scan or partner opened your information.": "ہر بار جب کسی ڈاکٹر، شیئر لنک، ہنگامی اسکین یا شراکت دار نے آپ کی معلومات کھولیں۔",
  "Every verified record from every doctor, newest first. Ask AI to explain any record in plain language.": "ہر ڈاکٹر کا ہر تصدیق شدہ ریکارڈ، تازہ ترین پہلے۔ کسی بھی ریکارڈ کو آسان زبان میں سمجھنے کے لیے اے آئی سے پوچھیں۔",
  "Everything booked with you, grouped by day.": "آپ کے ساتھ بُک ہر اپوائنٹمنٹ، دن کے لحاظ سے۔",
  "Existing bookings on a day off are not cancelled automatically.": "چھٹی کے دن کی موجودہ بُکنگز خود بخود منسوخ نہیں ہوتیں۔",
  "Expired": "میعاد ختم",
  "Expires after": "میعاد",
  "Explain": "سمجھائیں",
  "Export all": "سب ایکسپورٹ کریں",
  "Extracted text": "نکالا گیا متن",
  "Fair": "مناسب",
  "Family": "خاندان",
  "Family history": "خاندانی ہسٹری",
  "Family profile": "خاندانی پروفائل",
  "Family profiles": "خاندانی پروفائلز",
  "Father": "والد",
  "Features": "خصوصیات",
  "Fee": "فیس",
  "Fee on request": "فیس دریافت کریں",
  "Fees collected": "وصول شدہ فیس",
  "Female": "خاتون",
  "File is larger than 4 MB": "فائل 4 ایم بی سے بڑی ہے",
  "Files": "فائلیں",
  "Filled in from your document. Edit anything that looks wrong.": "آپ کی دستاویز سے بھرا گیا۔ جو غلط لگے اس میں ترمیم کریں۔",
  "Filter by category": "زمرے کے لحاظ سے چھانٹیں",
  "Find": "تلاش کریں",
  "Find a doctor": "ڈاکٹر تلاش کریں",
  "Find a test": "ٹیسٹ تلاش کریں",
  "Find a test, e.g. HbA1c": "ٹیسٹ تلاش کریں، مثلاً HbA1c",
  "Find a verified doctor": "تصدیق شدہ ڈاکٹر تلاش کریں",
  "Find doctors": "ڈاکٹر تلاش کریں",
  "Find your doctors and link them. Access is granted per doctor, never to everyone.": "اپنے ڈاکٹر تلاش کر کے انہیں منسلک کریں۔ رسائی ہر ڈاکٹر کو الگ دی جاتی ہے، سب کو کبھی نہیں۔",
  "First name": "پہلا نام",
  "Follow-up": "فالو اپ",
  "Follow-ups": "فالو اپس",
  "For doctors": "ڈاکٹروں کے لیے",
  "For patients": "مریضوں کے لیے",
  "For your safety we won't show this link again. Create a new one if you lose it.": "آپ کی حفاظت کے لیے یہ لنک دوبارہ نہیں دکھایا جائے گا۔ گم ہو جائے تو نیا بنا لیں۔",
  "Forgot password?": "پاس ورڈ بھول گئے؟",
  "Forgot your password?": "پاس ورڈ بھول گئے؟",
  "Former patient": "سابق مریض",
  "Four times daily": "دن میں چار بار",
  "Frequency": "کتنی بار",
  "Fri": "جمعہ",
  "Friday": "جمعہ",
  "Front desk": "استقبالیہ",
  "Front-desk accounts manage the schedule only. Medical records stay private to the patient and their doctors.": "استقبالیہ اکاؤنٹس صرف شیڈول سنبھالتے ہیں۔ طبی ریکارڈ صرف مریض اور اس کے ڈاکٹروں تک محدود رہتا ہے۔",
  "Front-desk sign-in": "استقبالیہ سائن اِن",
  "Front-desk staff": "استقبالیہ عملہ",
  "Gastroenterology": "امراضِ معدہ",
  "Gender": "جنس",
  "General": "عمومی",
  "General Physician": "جنرل فزیشن",
  "Generated by AI from your PakMedRecord data. It can make mistakes — confirm anything important with a doctor.": "آپ کے پاک میڈ ریکارڈ ڈیٹا سے اے آئی نے تیار کیا۔ اس میں غلطی ہو سکتی ہے — اہم بات کی ڈاکٹر سے تصدیق کریں۔",
  "Get a new link": "نیا لنک حاصل کریں",
  "Get started": "شروع کریں",
  "Get your PMDC registration verified on your Profile page first.": "پہلے اپنے پروفائل صفحے پر پی ایم ڈی سی رجسٹریشن کی تصدیق کروائیں۔",
  "Getting started": "آغاز",
  "Give a doctor temporary access to your history, and make sure emergency responders can see what matters.": "کسی ڈاکٹر کو اپنی ہسٹری تک عارضی رسائی دیں، اور یقینی بنائیں کہ ہنگامی امداد والے ضروری معلومات دیکھ سکیں۔",
  "Give them their own login": "انہیں اپنا لاگ اِن دیں",
  "Given": "لگ چکی",
  "Glucose": "شوگر",
  "Go back": "واپس جائیں",
  "Go to sign in": "سائن اِن پر جائیں",
  "Good": "اچھا",
  "Good afternoon": "سہ پہر بخیر",
  "Good evening": "شام بخیر",
  "Good morning": "صبح بخیر",
  "Google sign-in was interrupted. Please try again.": "گوگل سائن اِن میں خلل آیا۔ دوبارہ کوشش کریں۔",
  "Grandparent": "دادا/نانا",
  "Grow your care team": "اپنی کیئر ٹیم بڑھائیں",
  "Gynaecology": "امراضِ نسواں",
  "Has access": "رسائی حاصل ہے",
  "Health profile": "ہیلتھ پروفائل",
  "Health profile saved": "ہیلتھ پروفائل محفوظ ہو گیا",
  "Health records": "صحت کا ریکارڈ",
  "Health snapshot": "صحت کا خلاصہ",
  "Healthy": "صحت مند",
  "Heart disease": "دل کی بیماری",
  "Heart rate": "دل کی دھڑکن",
  "Height (cm)": "قد (سینٹی میٹر)",
  "Hi,": "السلام علیکم،",
  "Hide password": "پاس ورڈ چھپائیں",
  "High": "زیادہ",
  "Highlights use general adult reference ranges and aren't a diagnosis.": "نشاندہی بالغوں کی عمومی حدود پر مبنی ہے اور یہ تشخیص نہیں۔",
  "History": "ہسٹری",
  "History, findings, advice, follow-up…": "ہسٹری، معائنے کے نتائج، مشورہ، فالو اپ…",
  "Home": "ہوم",
  "Hospital": "ہسپتال",
  "Hour": "گھنٹہ",
  "How can I help with your clinic?": "میں آپ کے کلینک میں کیسے مدد کر سکتا ہوں؟",
  "How has my blood pressure been trending?": "میرا بلڈ پریشر کیسا رہا ہے؟",
  "How it works": "یہ کیسے کام کرتا ہے",
  "How often": "کتنی بار",
  "Hypertension": "ہائی بلڈ پریشر",
  "I agree to the": "میں متفق ہوں:",
  "I can look up your schedule, review queue and the history of your patients.": "میں آپ کا شیڈول، جائزے کی قطار اور آپ کے مریضوں کی ہسٹری دیکھ سکتا ہوں۔",
  "I can read your records, appointments and vitals, explain them in plain language, and book or log things for you.": "میں آپ کا ریکارڈ، اپوائنٹمنٹس اور وائٹلز پڑھ کر آسان زبان میں سمجھا سکتا ہوں، اور آپ کے لیے بُکنگ یا اندراج کر سکتا ہوں۔",
  "I'm a doctor": "میں ڈاکٹر ہوں",
  "If an account matches, we sent a link to reset your password. It works for one hour.": "اگر کوئی اکاؤنٹ ملتا ہے تو ہم نے پاس ورڈ ری سیٹ کا لنک بھیج دیا ہے۔ یہ ایک گھنٹے کے لیے کارآمد ہے۔",
  "If you lose your phone, each code lets you sign in once. Keep them somewhere safe; they won't be shown again.": "فون گم ہونے پر ہر کوڈ سے ایک بار سائن اِن کیا جا سکتا ہے۔ انہیں محفوظ جگہ رکھیں؛ یہ دوبارہ نہیں دکھائے جائیں گے۔",
  "Image": "تصویر",
  "Imaging": "امیجنگ",
  "In person": "بالمشافہ",
  "In your team": "آپ کی ٹیم میں",
  "Inappropriate behaviour": "نامناسب رویہ",
  "Inbox zero": "سب نمٹ گیا",
  "Include health profile (allergies, conditions, medicines)": "ہیلتھ پروفائل شامل کریں (الرجی، امراض، دوائیں)",
  "Include vitals": "وائٹلز شامل کریں",
  "Including childhood vaccines like polio and boosters.": "بچپن کی ویکسینز جیسے پولیو اور بوسٹرز سمیت۔",
  "Insights": "تجزیہ",
  "Insights appear once patients start booking appointments with you.": "مریضوں کے آپ سے وقت لینے پر تجزیہ نظر آئے گا۔",
  "Instant approvals": "فوری منظوری",
  "Instant booking": "فوری بُکنگ",
  "Instructions": "ہدایات",
  "Instructions (e.g. after meals)": "ہدایات (مثلاً کھانے کے بعد)",
  "Invitation declined": "دعوت مسترد",
  "Invitation sent": "دعوت بھیج دی گئی",
  "Invite": "مدعو کریں",
  "Issue API key": "اے پی آئی کلید جاری کریں",
  "Issue a key to a lab or pharmacy. Share the Developers page with them.": "لیبارٹری یا فارمیسی کو کلید جاری کریں۔ ڈیولپرز صفحہ ان کے ساتھ شیئر کریں۔",
  "Issue anyway": "پھر بھی جاری کریں",
  "Issue prescription": "نسخہ جاری کریں",
  "It takes less than a minute.": "ایک منٹ سے بھی کم وقت لگتا ہے۔",
  "It waits in their review queue.": "یہ ان کی جائزے کی قطار میں انتظار کرتا ہے۔",
  "It will be removed from the patient’s history. Use this only to correct a mistake.": "یہ مریض کی ہسٹری سے ہٹا دیا جائے گا۔ اسے صرف غلطی درست کرنے کے لیے استعمال کریں۔",
  "Join from the app at your time": "اپنے وقت پر ایپ سے شامل ہوں",
  "Join opens 15 min before": "شمولیت 15 منٹ پہلے کھلتی ہے",
  "Join video": "ویڈیو میں شامل ہوں",
  "Joined": "شمولیت",
  "Joining an existing clinic? Ask its admin to invite your CNIC; the invitation will appear here.": "کسی موجودہ کلینک میں شامل ہونا ہے؟ اس کے ایڈمن سے اپنے شناختی کارڈ پر دعوت بھیجنے کا کہیں؛ دعوت یہاں نظر آئے گی۔",
  "Jot down symptoms, questions for your next visit or medication reminders. Visible only to you.": "علامات، اگلے معائنے کے سوالات یا دوا کی یاد دہانیاں لکھیں۔ یہ صرف آپ کو نظر آتے ہیں۔",
  "Jump to…": "جائیں…",
  "Kaise madad karun?": "کیسے مدد کروں؟",
  "Keep a list of your allergies and medicines in your notes for emergencies.": "ہنگامی صورت کے لیے اپنی الرجی اور دواؤں کی فہرست نوٹس میں رکھیں۔",
  "Keep it": "رہنے دیں",
  "Keep your children's and parents' records under your login. Switch to a profile to see records, book appointments and track vaccines for them.": "اپنے بچوں اور والدین کا ریکارڈ اپنے لاگ اِن میں رکھیں۔ ان کا ریکارڈ دیکھنے، وقت لینے اور ویکسین ٹریک کرنے کے لیے ان کے پروفائل پر جائیں۔",
  "Key": "کلید",
  "Key copied": "کلید کاپی ہو گئی",
  "Lab result": "لیب رپورٹ",
  "Lab results": "لیب رپورٹس",
  "Lab trends": "لیب رجحانات",
  "Laboratory": "لیبارٹری",
  "Labs & pharmacies": "لیبارٹریز اور فارمیسیز",
  "Languages": "زبانیں",
  "Last 15 days and next 14": "گزشتہ 15 اور اگلے 14 دن",
  "Last name": "آخری نام",
  "Last used": "آخری استعمال",
  "Leave": "چھوڑیں",
  "Leave blank to keep current": "موجودہ رکھنے کے لیے خالی چھوڑیں",
  "Leave call": "کال چھوڑیں",
  "Leave this clinic?": "یہ کلینک چھوڑیں؟",
  "Light theme": "لائٹ تھیم",
  "Link copied": "لنک کاپی ہو گیا",
  "Link expired": "لنک کی میعاد ختم",
  "Link not valid": "لنک درست نہیں",
  "Link revoked": "لنک منسوخ",
  "Link the doctors you trust. Only they can open your records, and you can remove access at any time.": "جن ڈاکٹروں پر بھروسہ ہے انہیں منسلک کریں۔ صرف وہی آپ کا ریکارڈ کھول سکتے ہیں، اور آپ کسی بھی وقت رسائی ختم کر سکتے ہیں۔",
  "Link your first doctor": "اپنا پہلا ڈاکٹر منسلک کریں",
  "Loading your day…": "آپ کا دن لوڈ ہو رہا ہے…",
  "Log blood pressure, sugar, weight and more. Your care team can see the trends.": "بلڈ پریشر، شوگر، وزن وغیرہ درج کریں۔ آپ کی کیئر ٹیم رجحانات دیکھ سکتی ہے۔",
  "Log your first reading to start a trend.": "رجحان شروع کرنے کے لیے اپنی پہلی ریڈنگ درج کریں۔",
  "Long-term conditions you're managing.": "طویل مدتی امراض جن کا آپ علاج کر رہے ہیں۔",
  "Low": "کم",
  "Lower limit": "نچلی حد",
  "Main": "مرکزی",
  "Make time for something you enjoy every day. Your mental health matters.": "ہر روز اپنی پسند کے کام کے لیے وقت نکالیں۔ آپ کی ذہنی صحت اہم ہے۔",
  "Male": "مرد",
  "Mark all read": "سب کو پڑھا ہوا کریں",
  "Mark given": "لگ گئی",
  "Mark no-show": "غیر حاضر کریں",
  "Mark resolved": "حل شدہ کریں",
  "Marked as completed": "مکمل کر دیا گیا",
  "Marked as no-show": "غیر حاضر درج",
  "Marked high": "زیادہ درج",
  "Marked low": "کم درج",
  "Medical": "طبی",
  "Medical history": "طبی ہسٹری",
  "Medications": "دوائیں",
  "Medicine": "دوا",
  "Medicine & vaccine reminders": "دوا اور ویکسین کی یاد دہانیاں",
  "Medicine name": "دوا کا نام",
  "Medicine tracker": "دوا ٹریکر",
  "Medicines": "دوائیں",
  "Medicines, foods or anything else you react to.": "دوائیں، کھانے یا کوئی بھی چیز جس سے آپ کو ردعمل ہوتا ہو۔",
  "Member since": "رکنیت از",
  "Message the assistant": "اسسٹنٹ کو پیغام بھیجیں",
  "Migraine": "درد شقیقہ",
  "Missed": "چھوٹ گیا",
  "Missing payment reference": "ادائیگی کا حوالہ موجود نہیں",
  "Mon": "پیر",
  "Monday": "پیر",
  "Most": "زیادہ تر",
  "Mother": "والدہ",
  "Mute": "آواز بند کریں",
  "My appointments": "میری اپوائنٹمنٹس",
  "My care team": "میری کیئر ٹیم",
  "My clinic": "میرا کلینک",
  "My medical record": "میرا طبی ریکارڈ",
  "My medicines": "میری دوائیں",
  "My submissions": "میری جمع کردہ چیزیں",
  "Name": "نام",
  "Name or hospital": "نام یا ہسپتال",
  "Name, email or CNIC": "نام، ای میل یا شناختی کارڈ",
  "Name, email, PMDC no. or CNIC": "نام، ای میل، پی ایم ڈی سی نمبر یا شناختی کارڈ",
  "Name, specialty or hospital": "نام، شعبہ یا ہسپتال",
  "Needs your review": "آپ کے جائزے کا منتظر",
  "Nephrology": "امراضِ گردہ",
  "Neurology": "اعصابی امراض",
  "Never": "کبھی نہیں",
  "New QR code created. Print a new card; the old one no longer works.": "نیا کیو آر کوڈ بن گیا۔ نیا کارڈ پرنٹ کریں؛ پرانا اب کام نہیں کرے گا۔",
  "New booking": "نئی بُکنگ",
  "New chat": "نئی گفتگو",
  "New code": "نیا کوڈ",
  "New doctors (30 days)": "نئے ڈاکٹر (30 دن)",
  "New link": "نیا لنک",
  "New medical record": "نیا طبی ریکارڈ",
  "New note": "نیا نوٹ",
  "New password": "نیا پاس ورڈ",
  "New patients (30 days)": "نئے مریض (30 دن)",
  "New record": "نیا ریکارڈ",
  "New share link": "نیا شیئر لنک",
  "New to PakMedRecord?": "پاک میڈ ریکارڈ پر نئے ہیں؟",
  "Next": "اگلا",
  "Next appointment": "اگلی اپوائنٹمنٹ",
  "Next available": "اگلا دستیاب وقت",
  "Next day": "اگلا دن",
  "Next refill": "اگلی بار دوا لینی ہے",
  "Next tip": "اگلا مشورہ",
  "No access": "رسائی نہیں",
  "No accounts found": "کوئی اکاؤنٹ نہیں ملا",
  "No appointments": "کوئی اپوائنٹمنٹ نہیں",
  "No appointments in this view.": "اس منظر میں کوئی اپوائنٹمنٹ نہیں۔",
  "No appointments match your search.": "آپ کی تلاش سے کوئی اپوائنٹمنٹ نہیں ملی۔",
  "No certificate uploaded yet.": "ابھی کوئی سرٹیفکیٹ اپ لوڈ نہیں ہوا۔",
  "No data yet": "ابھی کوئی ڈیٹا نہیں",
  "No doctors found": "کوئی ڈاکٹر نہیں ملا",
  "No doctors have registered yet.": "ابھی کسی ڈاکٹر نے رجسٹریشن نہیں کی۔",
  "No doctors with this status.": "اس حیثیت کا کوئی ڈاکٹر نہیں۔",
  "No dose schedule yet. Adherence appears once medicines have dose times and doses are ticked off.": "ابھی خوراک کا شیڈول نہیں۔ دواؤں کے اوقات طے ہونے اور خوراکیں نشان زد کرنے پر پابندی کی شرح نظر آئے گی۔",
  "No dose times": "خوراک کے اوقات نہیں",
  "No doses scheduled": "کوئی خوراک طے نہیں",
  "No e-prescriptions yet": "ابھی کوئی ای نسخہ نہیں",
  "No email on file": "ای میل درج نہیں",
  "No errors": "کوئی خرابی نہیں",
  "No extracted text.": "کوئی متن نہیں نکلا۔",
  "No family members yet": "ابھی خاندان کا کوئی فرد نہیں",
  "No file? Start from a template": "فائل نہیں؟ نمونے سے شروع کریں",
  "No lab values yet": "ابھی لیب کے نتائج نہیں",
  "No links yet": "ابھی کوئی لنک نہیں",
  "No matches": "کچھ نہیں ملا",
  "No medications added.": "کوئی دوا شامل نہیں کی گئی۔",
  "No money was taken. You can try again or pay at the clinic.": "کوئی رقم نہیں کٹی۔ دوبارہ کوشش کریں یا کلینک پر ادائیگی کریں۔",
  "No notes yet": "ابھی کوئی نوٹ نہیں",
  "No one yet": "ابھی کوئی نہیں",
  "No open slots in the next two weeks.": "اگلے دو ہفتوں میں کوئی وقت خالی نہیں۔",
  "No partners yet": "ابھی کوئی شراکت دار نہیں",
  "No patients yet": "ابھی کوئی مریض نہیں",
  "No readings yet": "ابھی کوئی ریڈنگ نہیں",
  "No records shared.": "کوئی ریکارڈ شیئر نہیں کیا گیا۔",
  "No records waiting for approval.": "منظوری کا کوئی ریکارڈ منتظر نہیں۔",
  "No records yet": "ابھی کوئی ریکارڈ نہیں",
  "No records yet. Submit one or ask your doctor to add it.": "ابھی کوئی ریکارڈ نہیں۔ خود جمع کریں یا اپنے ڈاکٹر سے شامل کرنے کا کہیں۔",
  "No reports": "کوئی رپورٹ نہیں",
  "No saved conversations yet.": "ابھی کوئی محفوظ گفتگو نہیں۔",
  "No staff yet": "ابھی کوئی عملہ نہیں",
  "No text could be extracted from this file.": "اس فائل سے کوئی متن نہیں نکالا جا سکا۔",
  "No upcoming appointments": "کوئی آنے والی اپوائنٹمنٹ نہیں",
  "No upcoming appointments.": "کوئی آنے والی اپوائنٹمنٹ نہیں۔",
  "No upcoming days off.": "کوئی آنے والی چھٹی نہیں۔",
  "No vaccinations added.": "کوئی ویکسین شامل نہیں کی گئی۔",
  "No visits yet.": "ابھی کوئی معائنہ نہیں۔",
  "No-show": "غیر حاضر",
  "No-show rate": "غیر حاضری کی شرح",
  "None": "کوئی نہیں",
  "None recorded": "کچھ درج نہیں",
  "None recorded.": "کچھ درج نہیں۔",
  "None yet.": "ابھی کچھ نہیں۔",
  "Not a real doctor": "اصلی ڈاکٹر نہیں",
  "Not a valid prescription": "درست نسخہ نہیں",
  "Not found": "نہیں ملا",
  "Not scheduled": "طے نہیں",
  "Not working this day.": "اس دن کام نہیں کرتے۔",
  "Note": "نوٹ",
  "Note (optional)": "نوٹ (اختیاری)",
  "Note deleted": "نوٹ حذف ہو گیا",
  "Note saved": "نوٹ محفوظ ہو گیا",
  "Note to the doctor (required to reject)": "ڈاکٹر کے لیے نوٹ (مسترد کرنے کے لیے ضروری)",
  "Notes": "نوٹس",
  "Notes for the patient (optional)": "مریض کے لیے نوٹس (اختیاری)",
  "Notes saved and visit completed": "نوٹس محفوظ اور معائنہ مکمل",
  "Notes saved to the patient record": "نوٹس مریض کے ریکارڈ میں محفوظ",
  "Nothing booked for this day yet.": "اس دن کے لیے ابھی کچھ بُک نہیں۔",
  "Nothing booked.": "کچھ بُک نہیں۔",
  "Nothing here": "یہاں کچھ نہیں",
  "Nothing here yet": "یہاں ابھی کچھ نہیں",
  "Nothing looks overdue. We check your records, medicines, vaccines and lab results.": "کچھ بھی تاخیر کا شکار نہیں لگتا۔ ہم آپ کا ریکارڈ، دوائیں، ویکسینز اور لیب نتائج جانچتے ہیں۔",
  "Nothing to review right now. New submissions will appear here.": "ابھی جائزے کے لیے کچھ نہیں۔ نئی جمع کردہ چیزیں یہاں نظر آئیں گی۔",
  "Notifications": "اطلاعات",
  "Obese": "موٹاپا",
  "Off": "بند",
  "On": "آن",
  "Once approved, it joins your record with the original file.": "منظوری کے بعد یہ اصل فائل کے ساتھ آپ کے ریکارڈ میں شامل ہو جاتا ہے۔",
  "Once daily": "دن میں ایک بار",
  "Oncology": "سرطان کا شعبہ",
  "One last step before you can sign in.": "سائن اِن سے پہلے بس ایک آخری مرحلہ۔",
  "One lifelong record": "ایک تاحیات ریکارڈ",
  "One more step to keep your account safe.": "اکاؤنٹ کو محفوظ رکھنے کے لیے ایک اور مرحلہ۔",
  "One record.": "ایک ریکارڈ۔",
  "One-click record review": "ایک کلک میں ریکارڈ کا جائزہ",
  "Only doctors on your care team can open your records": "صرف آپ کی کیئر ٹیم کے ڈاکٹر آپ کا ریکارڈ کھول سکتے ہیں",
  "Only the prescribing doctor can cancel it": "صرف نسخہ لکھنے والا ڈاکٹر اسے منسوخ کر سکتا ہے",
  "Only you can see these. Use them for symptoms, questions for your doctor or medicine reminders.": "یہ صرف آپ دیکھ سکتے ہیں۔ علامات، ڈاکٹر کے لیے سوالات یا دوا کی یاد دہانی کے لیے استعمال کریں۔",
  "Open PakMed Assistant": "پاک میڈ اسسٹنٹ کھولیں",
  "Open menu": "مینو کھولیں",
  "Open note": "نوٹ کھولیں",
  "Open profile": "پروفائل کھولیں",
  "Open queue": "قطار کھولیں",
  "Open your authenticator app and enter the 6-digit code for PakMedRecord.": "اپنی تصدیقی ایپ کھول کر پاک میڈ ریکارڈ کا 6 ہندسوں کا کوڈ درج کریں۔",
  "Ophthalmology": "امراضِ چشم",
  "Optional. A photo of a prescription or a lab report PDF works. AI reads it and fills in step 2.": "اختیاری۔ نسخے کی تصویر یا لیب رپورٹ کی پی ڈی ایف چل جائے گی۔ اے آئی اسے پڑھ کر مرحلہ 2 بھر دیتا ہے۔",
  "Optional: the attached files are saved with their extracted text": "اختیاری: منسلک فائلیں نکالے گئے متن کے ساتھ محفوظ ہوتی ہیں",
  "Organisation name, e.g. Chughtai Lab": "ادارے کا نام، مثلاً چغتائی لیب",
  "Orthopaedics": "ہڈیوں کے امراض",
  "Other": "دیگر",
  "Overdue": "تاخیر شدہ",
  "Overview": "جائزہ",
  "Overweight": "زیادہ وزن",
  "Own login": "اپنا لاگ اِن",
  "Oxygen saturation": "آکسیجن کی سطح",
  "PDF or photo, up to 4 MB": "پی ڈی ایف یا تصویر، 4 ایم بی تک",
  "PDF with QR": "کیو آر والی پی ڈی ایف",
  "PMDC no.": "پی ایم ڈی سی نمبر",
  "PMDC registration number": "پی ایم ڈی سی رجسٹریشن نمبر",
  "PMDC registration verified by PakMedRecord": "پاک میڈ ریکارڈ سے تصدیق شدہ پی ایم ڈی سی رجسٹریشن",
  "PMDC verified": "پی ایم ڈی سی سے تصدیق شدہ",
  "Paediatrics": "امراضِ اطفال",
  "Paid": "ادا شدہ",
  "PakMed Assistant": "پاک میڈ اسسٹنٹ",
  "PakMedRecord admin": "پاک میڈ ریکارڈ ایڈمن",
  "Pakistan's unified health record": "پاکستان کا متحد صحت ریکارڈ",
  "Paramedics and ER staff scan it to see your blood group, allergies, conditions, medicines and emergency contact. Nothing else.": "پیرامیڈکس اور ایمرجنسی عملہ اسے اسکین کر کے آپ کا بلڈ گروپ، الرجی، امراض، دوائیں اور ہنگامی رابطہ دیکھ سکتے ہیں۔ اس کے سوا کچھ نہیں۔",
  "Partner": "شراکت دار",
  "Partners": "شراکت دار",
  "Password": "پاس ورڈ",
  "Password changed": "پاس ورڈ تبدیل ہو گیا",
  "Passwords are hashed and never leave the server": "پاس ورڈز محفوظ شکل میں رہتے ہیں اور کبھی سرور سے باہر نہیں جاتے",
  "Passwords don’t match": "پاس ورڈ میل نہیں کھاتے",
  "Past surgery": "سابقہ سرجری",
  "Patient": "مریض",
  "Patient CNIC": "مریض کا شناختی کارڈ",
  "Patient file": "مریض کی فائل",
  "Patient sign in": "مریض سائن اِن",
  "Patient-submitted": "مریض کا جمع کردہ",
  "Patient-submitted · verified": "مریض کا جمع کردہ · تصدیق شدہ",
  "Patients": "مریض",
  "Patients appear here once they add you to their care team from the doctor directory.": "مریض جب ڈاکٹر ڈائریکٹری سے آپ کو اپنی کیئر ٹیم میں شامل کریں گے تو یہاں نظر آئیں گے۔",
  "Patients can add you to their care team and you can see their records only after we check your PMDC registration.": "ہمارے آپ کی پی ایم ڈی سی رجسٹریشن جانچنے کے بعد ہی مریض آپ کو کیئر ٹیم میں شامل کر سکتے ہیں اور آپ ان کا ریکارڈ دیکھ سکتے ہیں۔",
  "Patients can choose a video visit for any open slot. You join from your Appointments page.": "مریض کسی بھی خالی وقت کے لیے ویڈیو معائنہ منتخب کر سکتے ہیں۔ آپ اپنے اپوائنٹمنٹس صفحے سے شامل ہوں گے۔",
  "Patients can only book the slots you open here. Add a second block for an evening clinic.": "مریض صرف وہی اوقات بُک کر سکتے ہیں جو آپ یہاں کھولیں۔ شام کے کلینک کے لیے دوسرا وقت شامل کریں۔",
  "Patients pay the price, re-explaining allergies, repeating tests, and losing reports between visits.": "نقصان مریض اٹھاتے ہیں: بار بار الرجی بتانا، ٹیسٹ دہرانا، اور معائنوں کے بیچ رپورٹس کھو دینا۔",
  "Patients see your specialty, fee, clinic and timings in the public doctor directory once you're verified.": "تصدیق کے بعد مریض عوامی ڈاکٹر ڈائریکٹری میں آپ کا شعبہ، فیس، کلینک اور اوقات دیکھ سکتے ہیں۔",
  "Patients seen": "دیکھے گئے مریض",
  "Patients who added you to their care team. Open a patient to see their complete history.": "وہ مریض جنہوں نے آپ کو اپنی کیئر ٹیم میں شامل کیا۔ مکمل ہسٹری دیکھنے کے لیے مریض کھولیں۔",
  "Pay at clinic": "کلینک پر ادائیگی",
  "Pay consultation fee": "مشاورتی فیس ادا کریں",
  "Pay online (test)": "آن لائن ادائیگی (ٹیسٹ)",
  "Pay online from My appointments, or at the clinic.": "میری اپوائنٹمنٹس سے آن لائن یا کلینک پر ادائیگی کریں۔",
  "Pay with JazzCash": "جاز کیش سے ادائیگی کریں",
  "Payment not completed": "ادائیگی مکمل نہیں ہوئی",
  "Payment pending": "ادائیگی زیر التوا",
  "Payment received": "ادائیگی موصول ہو گئی",
  "Payment recorded": "ادائیگی درج ہو گئی",
  "Peak hour": "مصروف ترین گھنٹہ",
  "Pending": "زیر التوا",
  "Pending review": "جائزہ زیر التوا",
  "Personal details": "ذاتی تفصیلات",
  "Pharmacies will see it as cancelled.": "فارمیسیوں کو یہ منسوخ نظر آئے گا۔",
  "Pharmacies with a PakMedRecord partner key can mark this prescription as dispensed through the partner API.": "پاک میڈ ریکارڈ شراکتی کلید رکھنے والی فارمیسیاں پارٹنر اے پی آئی کے ذریعے اس نسخے کو دی گئی دوا کے طور پر درج کر سکتی ہیں۔",
  "Pharmacy": "فارمیسی",
  "Phone": "فون",
  "Pick a day to see available times.": "دستیاب اوقات دیکھنے کے لیے دن منتخب کریں۔",
  "Pick a doctor from your care team, choose a slot, done. Doctors see it immediately in their queue.": "اپنی کیئر ٹیم سے ڈاکٹر چنیں، وقت چنیں، بس۔ ڈاکٹر اسے فوراً اپنی قطار میں دیکھ لیتے ہیں۔",
  "Pick a slot with your doctor": "اپنے ڈاکٹر کے ساتھ وقت منتخب کریں",
  "Please accept to continue": "جاری رکھنے کے لیے قبول کریں",
  "Please accept to create an account": "اکاؤنٹ بنانے کے لیے قبول کریں",
  "Please sign in": "براہ کرم سائن اِن کریں",
  "Please verify your email before signing in. Check your inbox for the link we sent.": "سائن اِن سے پہلے اپنی ای میل کی تصدیق کریں۔ ہمارا بھیجا ہوا لنک ان باکس میں دیکھیں۔",
  "Practice": "پریکٹس",
  "Practice performance": "پریکٹس کی کارکردگی",
  "Pre-consultation brief": "معائنے سے پہلے کا خلاصہ",
  "Prescribe": "نسخہ لکھیں",
  "Prescribed by": "نسخہ لکھنے والے",
  "Prescription": "نسخہ",
  "Prescription cancelled": "نسخہ منسوخ",
  "Prescription issued": "نسخہ جاری ہو گیا",
  "Prescription issued. The patient was notified and their medicine list updated.": "نسخہ جاری ہو گیا۔ مریض کو اطلاع دی گئی اور ان کی دواؤں کی فہرست اپ ڈیٹ ہو گئی۔",
  "Prescriptions": "نسخے",
  "Prescriptions your doctors write in PakMedRecord appear here with a QR code pharmacies can verify.": "آپ کے ڈاکٹروں کے پاک میڈ ریکارڈ میں لکھے نسخے یہاں کیو آر کوڈ کے ساتھ نظر آتے ہیں جسے فارمیسیاں تصدیق کر سکتی ہیں۔",
  "Press": "دبائیں",
  "Preview PDF": "پی ڈی ایف کا پیش منظر",
  "Preview page": "صفحے کا پیش منظر",
  "Previous": "پچھلا",
  "Previous day": "پچھلا دن",
  "Primary hospital": "بنیادی ہسپتال",
  "Print the wallet card and keep it with your CNIC, or save the QR as your phone's lock-screen image.": "بٹوے والا کارڈ پرنٹ کر کے شناختی کارڈ کے ساتھ رکھیں، یا کیو آر کو فون کی لاک اسکرین تصویر بنا لیں۔",
  "Privacy": "رازداری",
  "Privacy Policy": "رازداری کی پالیسی",
  "Privacy concern": "رازداری کا مسئلہ",
  "Private": "نجی",
  "Private notes": "نجی نوٹس",
  "Professional details": "پیشہ ورانہ تفصیلات",
  "Profile": "پروفائل",
  "Profile deleted": "پروفائل حذف ہو گیا",
  "Profile updated": "پروفائل اپ ڈیٹ ہو گیا",
  "Psychiatry": "نفسیاتی امراض",
  "Public profile": "عوامی پروفائل",
  "Pulmonology": "امراضِ پھیپھڑا",
  "Pulse": "نبض",
  "Qualifications": "قابلیت",
  "Questions about your health?": "اپنی صحت کے بارے میں سوالات؟",
  "Quick note": "فوری نوٹ",
  "Radiology": "ریڈیالوجی",
  "Re-enable": "دوبارہ فعال کریں",
  "Reading": "ریڈنگ",
  "Reading the document with AI…": "اے آئی دستاویز پڑھ رہا ہے…",
  "Reason (optional)": "وجہ (اختیاری)",
  "Reason (optional, shared with your doctor)": "وجہ (اختیاری، ڈاکٹر کو بتائی جائے گی)",
  "Reason (shared with the patient)": "وجہ (مریض کو بتائی جائے گی)",
  "Reason for the patient": "مریض کے لیے وجہ",
  "Reason for visit": "معائنے کی وجہ",
  "Reason for visit (optional)": "معائنے کی وجہ (اختیاری)",
  "Receipt": "رسید",
  "Receipt not available": "رسید دستیاب نہیں",
  "Recent patients": "حالیہ مریض",
  "Recent records": "حالیہ ریکارڈ",
  "Recent vitals": "حالیہ وائٹلز",
  "Receptionists get their own login to book walk-ins, check patients in and record payments. They can't see medical records.": "استقبالیہ عملے کو اپنا لاگ اِن ملتا ہے تاکہ وہ آنے والوں کی بُکنگ، حاضری اور ادائیگیاں درج کر سکیں۔ وہ طبی ریکارڈ نہیں دیکھ سکتے۔",
  "Record": "ریکارڈ",
  "Record added to patient history": "ریکارڈ مریض کی ہسٹری میں شامل ہو گیا",
  "Record approved": "ریکارڈ منظور",
  "Record deleted": "ریکارڈ حذف ہو گیا",
  "Record details": "ریکارڈ کی تفصیلات",
  "Record payment": "ادائیگی درج کریں",
  "Record rejected": "ریکارڈ مسترد",
  "Records": "ریکارڈ",
  "Records are reviewed by a doctor in your care team.": "ریکارڈ کا جائزہ آپ کی کیئر ٹیم کا ڈاکٹر لیتا ہے۔",
  "Records from every hospital, appointments and your care team, all tied to your CNIC.": "ہر ہسپتال کا ریکارڈ، اپوائنٹمنٹس اور کیئر ٹیم، سب آپ کے شناختی کارڈ سے منسلک۔",
  "Records you upload stay pending until your doctor reviews them, so your history is something clinicians can trust.": "آپ کے اپ لوڈ کردہ ریکارڈ ڈاکٹر کے جائزے تک زیر التوا رہتے ہیں، تاکہ آپ کی ہسٹری قابلِ اعتماد رہے۔",
  "Records your patients submitted. Approve to add them to their permanent history.": "آپ کے مریضوں کے جمع کردہ ریکارڈ۔ مستقل ہسٹری میں شامل کرنے کے لیے منظور کریں۔",
  "Records, appointments and approvals live in one place, ready for any doctor you visit.": "ریکارڈ، اپوائنٹمنٹس اور منظوریاں ایک جگہ، کسی بھی ڈاکٹر کے لیے تیار۔",
  "Recovery code": "بحالی کوڈ",
  "Reject": "مسترد کریں",
  "Reject record": "ریکارڈ مسترد کریں",
  "Reject this record?": "یہ ریکارڈ مسترد کریں؟",
  "Rejected": "مسترد",
  "Relation": "رشتہ",
  "Reminders": "یاد دہانیاں",
  "Remove": "ہٹائیں",
  "Remove a doctor and their access ends instantly": "ڈاکٹر ہٹاتے ہی ان کی رسائی فوراً ختم",
  "Remove block": "وقت ہٹائیں",
  "Remove day off": "چھٹی ہٹائیں",
  "Remove medication": "دوا ہٹائیں",
  "Remove medicine": "دوا ہٹائیں",
  "Remove staff": "عملہ ہٹائیں",
  "Remove this doctor?": "یہ ڈاکٹر ہٹائیں؟",
  "Remove time": "وقت ہٹائیں",
  "Remove vaccination": "ویکسین ہٹائیں",
  "Removed": "ہٹا دیا گیا",
  "Report updated": "رپورٹ اپ ڈیٹ ہو گئی",
  "Reports": "رپورٹس",
  "Reports get lost. Files stay behind at the last hospital. PakMedRecord gives every patient a single, doctor-verified record that travels with them, wherever they're treated.": "رپورٹس گم ہو جاتی ہیں۔ فائلیں پچھلے ہسپتال میں رہ جاتی ہیں۔ پاک میڈ ریکارڈ ہر مریض کو ایک ڈاکٹر سے تصدیق شدہ ریکارڈ دیتا ہے جو علاج کی ہر جگہ اس کے ساتھ رہتا ہے۔",
  "Required": "ضروری",
  "Rescue 1122": "ریسکیو 1122",
  "Resend email": "ای میل دوبارہ بھیجیں",
  "Resend verification email": "تصدیقی ای میل دوبارہ بھیجیں",
  "Restore": "بحال کریں",
  "Restore this account?": "یہ اکاؤنٹ بحال کریں؟",
  "Retry": "دوبارہ کوشش",
  "Returning patients": "دوبارہ آنے والے مریض",
  "Review": "جائزہ لیں",
  "Review queue": "جائزے کی قطار",
  "Reviewing doctor": "جائزہ لینے والا ڈاکٹر",
  "Revoke": "منسوخ کریں",
  "Revoked": "منسوخ",
  "Room, building, area": "کمرہ، عمارت، علاقہ",
  "Sat": "ہفتہ",
  "Saturday": "ہفتہ",
  "Save": "محفوظ کریں",
  "Save & complete visit": "محفوظ کریں اور معائنہ مکمل کریں",
  "Save changes": "تبدیلیاں محفوظ کریں",
  "Save hours": "اوقات محفوظ کریں",
  "Save note": "نوٹ محفوظ کریں",
  "Save notes": "نوٹس محفوظ کریں",
  "Save password": "پاس ورڈ محفوظ کریں",
  "Save reading": "ریڈنگ محفوظ کریں",
  "Save schedule": "شیڈول محفوظ کریں",
  "Save your recovery codes": "اپنے بحالی کوڈز محفوظ کریں",
  "Saved": "محفوظ ہو گیا",
  "Scan the QR code with your authenticator app, then enter the 6-digit code it shows.": "اپنی تصدیقی ایپ سے کیو آر کوڈ اسکین کریں، پھر دکھایا گیا 6 ہندسوں کا کوڈ درج کریں۔",
  "Schedule": "شیڈول",
  "Schedule saved": "شیڈول محفوظ ہو گیا",
  "Scheduled": "طے شدہ",
  "Scheduling": "وقت کا تعین",
  "Search": "تلاش",
  "Search doctors": "ڈاکٹر تلاش کریں",
  "Search name, CNIC, hospital": "نام، شناختی کارڈ، ہسپتال تلاش کریں",
  "Search pages": "صفحات تلاش کریں",
  "Search patient or CNIC": "مریض یا شناختی کارڈ تلاش کریں",
  "Search records, doctors, hospitals…": "ریکارڈ، ڈاکٹر، ہسپتال تلاش کریں…",
  "Security": "سیکیورٹی",
  "Security & privacy": "سیکیورٹی اور رازداری",
  "See all": "سب دیکھیں",
  "See your patients’ full history, review submitted records and manage your day.": "اپنے مریضوں کی مکمل ہسٹری دیکھیں، جمع کردہ ریکارڈ کا جائزہ لیں اور اپنا دن منظم کریں۔",
  "Seen": "دیکھے گئے",
  "Select a patient": "مریض منتخب کریں",
  "Select a patient to attach files.": "فائلیں منسلک کرنے کے لیے مریض منتخب کریں۔",
  "Send": "بھیجیں",
  "Send a report for approval": "منظوری کے لیے رپورٹ بھیجیں",
  "Send reset link": "ری سیٹ لنک بھیجیں",
  "Send them by": "بھیجنے کا ذریعہ",
  "Send to your doctor": "اپنے ڈاکٹر کو بھیجیں",
  "Sent for review. You’ll be notified when your doctor responds.": "جائزے کے لیے بھیج دیا گیا۔ ڈاکٹر کے جواب پر آپ کو اطلاع ملے گی۔",
  "Separate with commas": "کوما سے الگ کریں",
  "Server errors (24h)": "سرور کی خرابیاں (24 گھنٹے)",
  "Set dose times for your medicines below to track them here.": "یہاں ٹریک کرنے کے لیے نیچے اپنی دواؤں کے اوقات طے کریں۔",
  "Set up two-step sign-in": "دو مرحلہ سائن اِن ترتیب دیں",
  "Set up your clinic": "اپنا کلینک ترتیب دیں",
  "Share": "شیئر کریں",
  "Share link QR code": "شیئر لنک کا کیو آر کوڈ",
  "Share with any doctor": "کسی بھی ڈاکٹر سے شیئر کریں",
  "Sharing": "شیئرنگ",
  "Sharing & emergency": "شیئرنگ اور ہنگامی کارڈ",
  "Show password": "پاس ورڈ دکھائیں",
  "Shown on your emergency card.": "آپ کے ہنگامی کارڈ پر دکھایا جاتا ہے۔",
  "Sibling": "بہن/بھائی",
  "Sign in": "سائن اِن",
  "Sign in failed": "سائن اِن ناکام",
  "Sign in to book": "وقت لینے کے لیے سائن اِن کریں",
  "Sign in to your doctor dashboard.": "اپنے ڈاکٹر ڈیش بورڈ میں سائن اِن کریں۔",
  "Sign in to your patient dashboard.": "اپنے مریض ڈیش بورڈ میں سائن اِن کریں۔",
  "Sign in with your new password": "نئے پاس ورڈ سے سائن اِن کریں",
  "Sign out": "سائن آؤٹ",
  "Sign out?": "سائن آؤٹ کریں؟",
  "Sign up failed": "سائن اپ ناکام",
  "Sign up with your CNIC. It becomes your universal health ID across every hospital.": "اپنے شناختی کارڈ سے سائن اپ کریں۔ یہ ہر ہسپتال میں آپ کی صحت کی شناخت بن جاتا ہے۔",
  "Signed sessions that expire automatically": "خود بخود ختم ہونے والے محفوظ سیشن",
  "Since": "از",
  "Skipped": "چھوڑ دی",
  "Some": "کچھ",
  "Something went wrong": "کچھ غلط ہو گیا",
  "Son": "بیٹا",
  "Spam": "اسپام",
  "Specialization": "شعبہ",
  "Specialty": "شعبہ",
  "Specialty / hospital": "شعبہ / ہسپتال",
  "Spouse": "شریکِ حیات",
  "Staff account created": "عملے کا اکاؤنٹ بن گیا",
  "Staff sign-in": "عملہ سائن اِن",
  "Start over": "دوبارہ شروع کریں",
  "Start video": "ویڈیو شروع کریں",
  "Starting camera…": "کیمرہ شروع ہو رہا ہے…",
  "Status": "حیثیت",
  "Stay hydrated. Aim for 8 glasses of water a day, more in Karachi summers.": "پانی کی کمی نہ ہونے دیں۔ روزانہ 8 گلاس پانی پئیں، کراچی کی گرمیوں میں زیادہ۔",
  "Stop generating": "جواب روکیں",
  "Stopped": "روک دیا",
  "Stroke": "فالج",
  "Strong": "مضبوط",
  "Submit a medical record": "طبی ریکارڈ جمع کریں",
  "Submit a record": "ریکارڈ جمع کریں",
  "Submit for review": "جائزے کے لیے جمع کریں",
  "Submit for verification": "تصدیق کے لیے جمع کریں",
  "Submit your first record": "اپنا پہلا ریکارڈ جمع کریں",
  "Submitted": "جمع شدہ",
  "Submitted records stay pending until approved.": "جمع کردہ ریکارڈ منظوری تک زیر التوا رہتے ہیں۔",
  "Summarise my health records": "میرے صحت کے ریکارڈ کا خلاصہ کریں",
  "Summary": "خلاصہ",
  "Sun": "اتوار",
  "Sunday": "اتوار",
  "Surgery": "سرجری",
  "Suspend": "معطل کریں",
  "Suspend this account?": "یہ اکاؤنٹ معطل کریں؟",
  "Suspended": "معطل",
  "Swap sugary drinks for water, lassi without sugar, or green tea.": "میٹھے مشروبات کی جگہ پانی، بغیر چینی کی لسی یا سبز چائے لیں۔",
  "Switch back to me": "اپنے پروفائل پر واپس جائیں",
  "Switch to dark theme": "ڈارک تھیم پر جائیں",
  "Switch to light theme": "لائٹ تھیم پر جائیں",
  "Symptoms, questions for your doctor, medicine reminders…": "علامات، ڈاکٹر کے لیے سوالات، دوا کی یاد دہانیاں…",
  "Systolic": "اوپر والا",
  "Table view": "ٹیبل منظر",
  "Take a photo": "تصویر لیں",
  "Taken": "لے لی",
  "Temperature": "بخار/درجہ حرارت",
  "Temporary password": "عارضی پاس ورڈ",
  "Terms": "شرائط",
  "Terms of Service": "سروس کی شرائط",
  "Test mode: no real payment": "ٹیسٹ موڈ: کوئی اصل ادائیگی نہیں",
  "Test names and results, medicines and doses, dates…": "ٹیسٹ کے نام اور نتائج، دوائیں اور خوراکیں، تاریخیں…",
  "Text": "متن",
  "Text copied": "متن کاپی ہو گیا",
  "Text was read automatically by AI. Check it against the original document.": "متن اے آئی نے خود پڑھا ہے۔ اسے اصل دستاویز سے ملا لیں۔",
  "That code is not right": "یہ کوڈ درست نہیں",
  "The EPI schedule covers children under 6. Adult vaccinations are listed in the health profile.": "ای پی آئی شیڈول 6 سال سے کم عمر بچوں کے لیے ہے۔ بالغوں کی ویکسینز ہیلتھ پروفائل میں درج ہیں۔",
  "The database is close to the 512 MB free-tier limit. Upgrade the Atlas cluster before it fills up.": "ڈیٹا بیس 512 ایم بی کی مفت حد کے قریب ہے۔ بھرنے سے پہلے اٹلس کلسٹر اپ گریڈ کریں۔",
  "The doctor can scan the QR code or open the link.": "ڈاکٹر کیو آر کوڈ اسکین کر سکتے ہیں یا لنک کھول سکتے ہیں۔",
  "The doctor isn't available on this day. Pick another day.": "ڈاکٹر اس دن دستیاب نہیں۔ کوئی اور دن منتخب کریں۔",
  "The essentials every doctor should know. Your care team sees this, and it powers your emergency card.": "وہ ضروری باتیں جو ہر ڈاکٹر کو معلوم ہونی چاہئیں۔ آپ کی کیئر ٹیم یہ دیکھتی ہے، اور اسی سے آپ کا ہنگامی کارڈ بنتا ہے۔",
  "The full text of each file is saved with the record too.": "ہر فائل کا مکمل متن بھی ریکارڈ کے ساتھ محفوظ ہوتا ہے۔",
  "The national childhood schedule with due dates worked out from the date of birth. We remind you a week before each one.": "قومی حفاظتی ٹیکوں کا شیڈول، تاریخ پیدائش سے حساب شدہ تاریخوں کے ساتھ۔ ہم ہر ٹیکے سے ایک ہفتہ پہلے یاد دلاتے ہیں۔",
  "The patient hasn’t logged this vital.": "مریض نے یہ وائٹل درج نہیں کیا۔",
  "The patient will be notified and will see your reason.": "مریض کو اطلاع دی جائے گی اور وہ آپ کی وجہ دیکھیں گے۔",
  "The patient will be notified.": "مریض کو اطلاع دی جائے گی۔",
  "The problem": "مسئلہ",
  "The server hasn't logged any errors in the last 30 days.": "سرور پر پچھلے 30 دنوں میں کوئی خرابی درج نہیں ہوئی۔",
  "The two passwords do not match": "دونوں پاس ورڈ میل نہیں کھاتے",
  "Their email": "ان کی ای میل",
  "These doctors can view your records and receive your appointments and submissions.": "یہ ڈاکٹر آپ کا ریکارڈ دیکھ سکتے ہیں اور آپ کی اپوائنٹمنٹس اور جمع کردہ چیزیں وصول کرتے ہیں۔",
  "They review it before it joins your permanent record.": "مستقل ریکارڈ میں شامل ہونے سے پہلے وہ اس کا جائزہ لیتے ہیں۔",
  "They sign in at /desk with this email and password.": "وہ اس ای میل اور پاس ورڈ سے /desk پر سائن اِن کرتے ہیں۔",
  "They will be able to sign in again.": "وہ دوبارہ سائن اِن کر سکیں گے۔",
  "They will be signed out and cannot sign in until restored.": "وہ سائن آؤٹ ہو جائیں گے اور بحالی تک سائن اِن نہیں کر سکیں گے۔",
  "They will immediately lose access to your records. You can add them again later.": "ان کی آپ کے ریکارڈ تک رسائی فوراً ختم ہو جائے گی۔ آپ بعد میں انہیں دوبارہ شامل کر سکتے ہیں۔",
  "They won't need their own login. You can give them one later.": "انہیں اپنے لاگ اِن کی ضرورت نہیں۔ آپ بعد میں انہیں دے سکتے ہیں۔",
  "Thinking": "سوچ رہا ہے",
  "This cannot be undone.": "یہ واپس نہیں ہو سکتا۔",
  "This file is larger than 4 MB. Try a smaller scan or a photo.": "یہ فائل 4 ایم بی سے بڑی ہے۔ چھوٹا اسکین یا تصویر آزمائیں۔",
  "This is a simulated checkout for trying out PakMedRecord. Clinics that connect Safepay send patients to Safepay's secure checkout instead.": "یہ پاک میڈ ریکارڈ آزمانے کے لیے فرضی ادائیگی ہے۔ جن کلینکس نے سیف پے منسلک کیا ہے وہاں مریض سیف پے کے محفوظ صفحے پر ادائیگی کرتے ہیں۔",
  "This patient hasn't added you to their care team.": "اس مریض نے آپ کو اپنی کیئر ٹیم میں شامل نہیں کیا۔",
  "This reset link is incomplete. Ask for a new one.": "یہ ری سیٹ لنک نامکمل ہے۔ نیا لنک منگوائیں۔",
  "This verification link is incomplete.": "یہ تصدیقی لنک نامکمل ہے۔",
  "This visit is not available": "یہ معائنہ دستیاب نہیں",
  "Three steps to a record that follows you.": "تین مراحل میں ایک ریکارڈ جو ہر جگہ آپ کے ساتھ رہے۔",
  "Three times daily": "دن میں تین بار",
  "Thu": "جمعرات",
  "Thursday": "جمعرات",
  "Tick off each dose, see how well you're keeping up, and get a reminder before you run out.": "ہر خوراک پر نشان لگائیں، دیکھیں آپ کتنی پابندی کر رہے ہیں، اور دوا ختم ہونے سے پہلے یاد دہانی پائیں۔",
  "Time": "وقت",
  "Timings": "اوقات",
  "Title": "عنوان",
  "To suspend a reported account, find it under Accounts.": "رپورٹ شدہ اکاؤنٹ معطل کرنے کے لیے اسے اکاؤنٹس میں تلاش کریں۔",
  "Today": "آج",
  "Today’s schedule, check-ins and walk-in bookings. Your clinic admin creates your account.": "آج کا شیڈول، حاضری اور آنے والوں کی بُکنگ۔ آپ کا اکاؤنٹ کلینک ایڈمن بناتا ہے۔",
  "Too weak": "بہت کمزور",
  "Total": "کل",
  "Total appointments": "کل اپوائنٹمنٹس",
  "Tracking": "ٹریکنگ",
  "Training, areas of interest, languages spoken…": "تربیت، دلچسپی کے شعبے، بولی جانے والی زبانیں…",
  "Trusted by doctors.": "ڈاکٹروں کا اعتماد۔",
  "Try a different search or category.": "کوئی اور تلاش یا زمرہ آزمائیں۔",
  "Try another city or specialty.": "کوئی اور شہر یا شعبہ آزمائیں۔",
  "Try another name or CNIC.": "کوئی اور نام یا شناختی کارڈ آزمائیں۔",
  "Try another name or hospital.": "کوئی اور نام یا ہسپتال آزمائیں۔",
  "Try box breathing for stress: in 4, hold 4, out 4, hold 4.": "ذہنی دباؤ کے لیے باکس بریدنگ آزمائیں: 4 تک سانس لیں، 4 روکیں، 4 میں نکالیں، 4 روکیں۔",
  "Tue": "منگل",
  "Tuesday": "منگل",
  "Turn camera off": "کیمرہ بند کریں",
  "Turn camera on": "کیمرہ آن کریں",
  "Turn it on to get your QR code. You can turn it off at any time and the code stops working immediately.": "اپنا کیو آر کوڈ حاصل کرنے کے لیے اسے آن کریں۔ آپ کسی بھی وقت اسے بند کر سکتے ہیں اور کوڈ فوراً کام کرنا چھوڑ دیتا ہے۔",
  "Turn off": "بند کریں",
  "Turn off two-step sign-in?": "دو مرحلہ سائن اِن بند کریں؟",
  "Turn on": "آن کریں",
  "Twice daily": "دن میں دو بار",
  "Two-step sign-in": "دو مرحلہ سائن اِن",
  "Two-step sign-in is off": "دو مرحلہ سائن اِن بند ہے",
  "Two-step sign-in is on": "دو مرحلہ سائن اِن آن ہے",
  "Type": "قسم",
  "Type 2 diabetes": "ٹائپ 2 ذیابیطس",
  "Type DELETE to confirm": "تصدیق کے لیے DELETE لکھیں",
  "Type an allergy and press Enter": "الرجی لکھ کر انٹر دبائیں",
  "Underweight": "کم وزن",
  "Undo": "واپس کریں",
  "Unknown": "نامعلوم",
  "Unknown doctor": "نامعلوم ڈاکٹر",
  "Unmute": "آواز کھولیں",
  "Upcoming": "آنے والی",
  "Upcoming appointments": "آنے والی اپوائنٹمنٹس",
  "Upcoming visits": "آنے والے معائنے",
  "Update your details. Your CNIC is your permanent health ID and can't be changed.": "اپنی تفصیلات اپ ڈیٹ کریں۔ آپ کا شناختی کارڈ آپ کی مستقل صحت کی شناخت ہے اور تبدیل نہیں ہو سکتا۔",
  "Upload PMDC certificate": "پی ایم ڈی سی سرٹیفکیٹ اپ لوڈ کریں",
  "Upload documents": "دستاویزات اپ لوڈ کریں",
  "Upload failed": "اپ لوڈ ناکام",
  "Upload failed. Check your connection.": "اپ لوڈ ناکام۔ اپنا انٹرنیٹ کنکشن چیک کریں۔",
  "Upload lab reports (PDF or photo) when submitting a record. The AI reads the values and they appear here as trends.": "ریکارڈ جمع کرتے وقت لیب رپورٹس (پی ڈی ایف یا تصویر) اپ لوڈ کریں۔ اے آئی نتائج پڑھتا ہے اور وہ یہاں رجحانات کی صورت میں نظر آتے ہیں۔",
  "Upload or type": "اپ لوڈ کریں یا لکھیں",
  "Upload the document": "دستاویز اپ لوڈ کریں",
  "Uploaded files": "اپ لوڈ شدہ فائلیں",
  "Upper limit": "بالائی حد",
  "Urdu, English, Sindhi": "اردو، انگریزی، سندھی",
  "Urology": "امراضِ مثانہ",
  "Use a different method": "کوئی اور طریقہ استعمال کریں",
  "Use a recovery code": "بحالی کوڈ استعمال کریں",
  "Use at least 6 characters": "کم از کم 6 حروف استعمال کریں",
  "Use at least 8 characters": "کم از کم 8 حروف استعمال کریں",
  "Use at least 8 characters. A mix of words, numbers and symbols is strongest.": "کم از کم 8 حروف استعمال کریں۔ الفاظ، ہندسوں اور علامات کا مرکب سب سے مضبوط ہے۔",
  "Use authenticator code": "تصدیقی کوڈ استعمال کریں",
  "Use if the call won't connect on your network": "اگر آپ کے نیٹ ورک پر کال نہ جڑے تو استعمال کریں",
  "Vaccination": "ویکسینیشن",
  "Vaccinations": "ویکسینیشنز",
  "Vaccine": "ویکسین",
  "Vaccines": "ویکسینز",
  "Valid · not yet dispensed": "درست · دوا ابھی نہیں دی گئی",
  "Value": "قدر",
  "Verification": "تصدیق",
  "Verification code": "تصدیقی کوڈ",
  "Verification failed": "تصدیق ناکام",
  "Verification in review": "تصدیق زیر جائزہ",
  "Verification needs attention": "تصدیق پر توجہ درکار",
  "Verified records will appear here as a timeline of the medical history.": "تصدیق شدہ ریکارڈ یہاں طبی ہسٹری کی ٹائم لائن کی صورت میں نظر آئیں گے۔",
  "Verify": "تصدیق کریں",
  "Verify now": "ابھی تصدیق کریں",
  "Verify your PMDC registration": "اپنی پی ایم ڈی سی رجسٹریشن کی تصدیق کروائیں",
  "Verify your PMDC registration so patients can add you and you can see their records.": "اپنی پی ایم ڈی سی رجسٹریشن کی تصدیق کروائیں تاکہ مریض آپ کو شامل کر سکیں اور آپ ان کا ریکارڈ دیکھ سکیں۔",
  "Verifying your email…": "آپ کی ای میل کی تصدیق ہو رہی ہے…",
  "Video": "ویڈیو",
  "Video call": "ویڈیو کال",
  "Video consultation": "ویڈیو مشاورت",
  "Video consultations": "ویڈیو مشاورت",
  "Video visit": "ویڈیو معائنہ",
  "Video visit with": "ویڈیو معائنہ:",
  "Video visits": "ویڈیو معائنے",
  "View records": "ریکارڈ دیکھیں",
  "View status": "حیثیت دیکھیں",
  "Views will appear here.": "دیکھنے کا ریکارڈ یہاں نظر آئے گا۔",
  "Visit": "معائنہ",
  "Visit type": "معائنے کی قسم",
  "Vitals": "وائٹلز",
  "Vitals at a glance": "وائٹلز ایک نظر میں",
  "Waiting": "منتظر",
  "Waiting (checked in)": "منتظر (حاضر)",
  "Waiting for your files to finish…": "فائلوں کے مکمل ہونے کا انتظار…",
  "Wash hands for 20 seconds, especially before meals and after travel.": "خاص طور پر کھانے سے پہلے اور سفر کے بعد 20 سیکنڈ ہاتھ دھوئیں۔",
  "We could not send the email to": "ہم ای میل نہیں بھیج سکے:",
  "We remind you the day before appointments, when medicines need a refill and when a child's vaccine is due.": "ہم اپوائنٹمنٹ سے ایک دن پہلے، دوا ختم ہونے پر اور بچے کی ویکسین کے وقت یاد دلاتے ہیں۔",
  "We sent a verification link to": "ہم نے تصدیقی لنک بھیجا ہے:",
  "Weak": "کمزور",
  "Wed": "بدھ",
  "Wednesday": "بدھ",
  "Weight": "وزن",
  "Weight (kg)": "وزن (کلوگرام)",
  "Welcome back": "خوش آمدید",
  "Welcome back.": "خوش آمدید۔",
  "Welcome to PakMedRecord": "پاک میڈ ریکارڈ میں خوش آمدید",
  "What": "کیا",
  "What do my latest lab results mean?": "میرے تازہ لیب نتائج کا کیا مطلب ہے؟",
  "What should I ask at my next appointment?": "اگلی اپوائنٹمنٹ پر مجھے کیا پوچھنا چاہیے؟",
  "What you take regularly, including supplements.": "جو آپ باقاعدگی سے لیتے ہیں، سپلیمنٹس سمیت۔",
  "WhatsApp": "واٹس ایپ",
  "When": "کب",
  "When do you take it each day?": "آپ روزانہ اسے کب لیتے ہیں؟",
  "When was it given?": "یہ کب لگی؟",
  "When your patients book, and how your schedule is trending.": "آپ کے مریض کب وقت لیتے ہیں، اور آپ کا شیڈول کیسا جا رہا ہے۔",
  "Where to?": "کہاں جانا ہے؟",
  "Which records are waiting for my review?": "کون سے ریکارڈ میرے جائزے کے منتظر ہیں؟",
  "Who": "کون",
  "Who is it for?": "یہ کس کے لیے ہے؟",
  "Who viewed my record": "میرا ریکارڈ کس نے دیکھا",
  "Write a note for your next visit": "اگلے معائنے کے لیے نوٹ لکھیں",
  "Write a note…": "نوٹ لکھیں…",
  "Write prescription": "نسخہ لکھیں",
  "Years of experience": "تجربہ (سال)",
  "You always get reminders in the app's notification bell.": "ایپ کی اطلاعات کی گھنٹی میں آپ کو ہمیشہ یاد دہانیاں ملتی ہیں۔",
  "You can book with doctors in your care team. Add one to get started.": "آپ اپنی کیئر ٹیم کے ڈاکٹروں سے وقت لے سکتے ہیں۔ شروع کرنے کے لیے ایک ڈاکٹر شامل کریں۔",
  "You can keep filling in the form while files are read.": "فائلیں پڑھے جانے کے دوران آپ فارم بھرتے رہ سکتے ہیں۔",
  "You have unsaved changes": "آپ کی تبدیلیاں محفوظ نہیں ہوئیں",
  "You left the call.": "آپ نے کال چھوڑ دی۔",
  "You left the clinic": "آپ نے کلینک چھوڑ دیا",
  "You submit": "آپ جمع کرتے ہیں",
  "You will need your CNIC and password to sign back in.": "دوبارہ سائن اِن کے لیے آپ کو شناختی کارڈ اور پاس ورڈ درکار ہوگا۔",
  "You're all caught up.": "سب کچھ نمٹ گیا۔",
  "You're booked!": "آپ کی بُکنگ ہو گئی!",
  "You're offline. Showing your last saved records; changes need a connection.": "آپ آف لائن ہیں۔ آخری محفوظ ریکارڈ دکھایا جا رہا ہے؛ تبدیلیوں کے لیے انٹرنیٹ درکار ہے۔",
  "You've been signed out everywhere else. Sign in with your new password.": "آپ ہر جگہ سے سائن آؤٹ ہو گئے ہیں۔ نئے پاس ورڈ سے سائن اِن کریں۔",
  "Your PMDC verification is in review. Patients can add you once it’s approved.": "آپ کی پی ایم ڈی سی تصدیق زیر جائزہ ہے۔ منظوری کے بعد مریض آپ کو شامل کر سکیں گے۔",
  "Your account has been deleted": "آپ کا اکاؤنٹ حذف ہو گیا",
  "Your account is active. You can sign in now.": "آپ کا اکاؤنٹ فعال ہے۔ اب آپ سائن اِن کر سکتے ہیں۔",
  "Your account is verified": "آپ کا اکاؤنٹ تصدیق شدہ ہے",
  "Your care team": "آپ کی کیئر ٹیم",
  "Your care team is empty": "آپ کی کیئر ٹیم خالی ہے",
  "Your clinic": "آپ کا کلینک",
  "Your clinic, finally connected.": "آپ کا کلینک، آخرکار مربوط۔",
  "Your complete medical history, care team and appointments, all in one record that travels with you.": "آپ کی مکمل طبی ہسٹری، کیئر ٹیم اور اپوائنٹمنٹس، سب ایک ریکارڈ میں جو آپ کے ساتھ رہتا ہے۔",
  "Your control.": "آپ کا اختیار۔",
  "Your data": "آپ کا ڈیٹا",
  "Your doctor has been notified.": "آپ کے ڈاکٹر کو اطلاع دے دی گئی ہے۔",
  "Your first note is one sentence away.": "آپ کا پہلا نوٹ بس ایک جملے کی دوری پر ہے۔",
  "Your health": "آپ کی صحت",
  "Your health companion": "آپ کا صحت کا ساتھی",
  "Your health, in one place.": "آپ کی صحت، ایک جگہ۔",
  "Your link is ready": "آپ کا لنک تیار ہے",
  "Your medical history.": "آپ کی طبی ہسٹری۔",
  "Your password": "آپ کا پاس ورڈ",
  "Your patients": "آپ کے مریض",
  "Your record goes to the doctor you choose.": "آپ کا ریکارڈ آپ کے منتخب ڈاکٹر کو جاتا ہے۔",
  "Your records.": "آپ کا ریکارڈ۔",
  "Your upcoming visits and history. Cancel anytime before the visit.": "آپ کے آنے والے معائنے اور ہسٹری۔ معائنے سے پہلے کسی بھی وقت منسوخ کریں۔",
  "cancelled": "منسوخ",
  "completed": "مکمل",
  "e.g. Aga Khan University Hospital": "مثلاً آغا خان یونیورسٹی ہسپتال",
  "e.g. Certificate image is blurry; please upload a clearer scan.": "مثلاً سرٹیفکیٹ کی تصویر دھندلی ہے؛ براہ کرم واضح اسکین اپ لوڈ کریں۔",
  "e.g. Clifton Family Clinic": "مثلاً کلفٹن فیملی کلینک",
  "e.g. Clinic closed — please rebook": "مثلاً کلینک بند ہے — دوبارہ وقت لیں",
  "e.g. Dr. Rehman, Liaquat National": "مثلاً ڈاکٹر رحمان، لیاقت نیشنل",
  "e.g. Essential hypertension": "مثلاً ہائی بلڈ پریشر",
  "e.g. Feeling better": "مثلاً طبیعت بہتر ہے",
  "e.g. Follow-up on blood test results, recurring headaches…": "مثلاً خون کے ٹیسٹ کا فالو اپ، بار بار سر درد…",
  "e.g. Hypertension": "مثلاً ہائی بلڈ پریشر",
  "e.g. Karachi": "مثلاً کراچی",
  "e.g. Review in 4 weeks with BP readings": "مثلاً 4 ہفتے بعد بلڈ پریشر کی ریڈنگز کے ساتھ دکھائیں",
  "e.g. Walk-in, fever": "مثلاً بغیر وقت کے آئے، بخار",
  "or tap the glowing button.": "یا چمکتے بٹن کو دبائیں۔",
  "or with your CNIC": "یا اپنے شناختی کارڈ سے",
  "paid": "ادا شدہ",
  "pending": "زیر التوا",
  "unpaid": "غیر ادا شدہ",
  "vaccines recorded": "ویکسینز درج",
  "← All doctors": "→ تمام ڈاکٹر",
};

const DAYS = { Sun: 'اتوار', Mon: 'پیر', Tue: 'منگل', Wed: 'بدھ', Thu: 'جمعرات', Fri: 'جمعہ', Sat: 'ہفتہ' };
const MONTHS = { Jan: 'جنوری', Feb: 'فروری', Mar: 'مارچ', Apr: 'اپریل', May: 'مئی', Jun: 'جون', Jul: 'جولائی', Aug: 'اگست', Sep: 'ستمبر', Oct: 'اکتوبر', Nov: 'نومبر', Dec: 'دسمبر' };
const tr = (s) => UR[s] || s;
const LONG_MONTHS = { January: 'جنوری', February: 'فروری', March: 'مارچ', April: 'اپریل', May: 'مئی', June: 'جون', July: 'جولائی', August: 'اگست', September: 'ستمبر', October: 'اکتوبر', November: 'نومبر', December: 'دسمبر' };
// time of day the way people say it: صبح / دوپہر / شام / رات
const partOfDay = (h24) => (h24 >= 4 && h24 < 12 ? 'صبح' : h24 < 16 ? 'دوپہر' : h24 < 19 ? 'شام' : 'رات');
const lookupTime = (t) => {
  const m = String(t).match(/^(\d+):(\d+) (AM|PM)$/);
  return m ? `${m[1]}:${m[2]} ${partOfDay(Number(m[1]) % 12 + (m[3] === 'PM' ? 12 : 0))}` : t;
};

// Phrases with values in them: [regex, (...groups) => urdu]
export const UR_PATTERNS = [
  [/^(\d+) active$/, (n) => `${n} فعال`],
  [/^Checked (.+)$/, (d) => `جانچ: ${d}`],
  [/^(\d+) taken · last (\d+) days$/, (a, b) => `${a} لی گئیں · گزشتہ ${b} دن`],
  [/^(.+) · (\d+)$/, (a, n) => `${tr(a)} · ${n}`],
  [/^Dr\. (.+)$/, (name) => `ڈاکٹر ${name}`],
  [/^(Good morning|Good afternoon|Good evening), (.+)$/, (g, name) => `${tr(g)}، ${name}`],
  [/^Welcome back, (.+)$/, (name) => `خوش آمدید، ${name}`],
  [/^(\d+) of (\d+) doses taken$/, (a, b) => `${b} میں سے ${a} خوراکیں لی گئیں`],
  [/^(\d+) slots?$/, (n) => `${n} اوقات`],
  [/^(\d+) min$/, (n) => `${n} منٹ`],
  [/^(\d+) days$/, (n) => `${n} دن`],
  [/^(\d+) years$/, (n) => `${n} سال`],
  [/^(\d+) months$/, (n) => `${n} ماہ`],
  [/^(\d+) hours?$/, (n) => `${n} گھنٹے`],
  [/^12 months$/, () => '12 ماہ'],
  [/^(\d+) doctors?$/, (n) => `${n} ڈاکٹر`],
  [/^Page (\d+) of (\d+)$/, (a, b) => `صفحہ ${a} از ${b}`],
  [/^Rs ([\d,]+)$/, (n) => `${n} روپے`],
  [/^(Mon|Tue|Wed|Thu|Fri|Sat|Sun)$/, (d) => DAYS[d]],
  [/^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)$/, (m) => MONTHS[m]],
  [/^(\d+) (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) (\d{4})$/, (d, m, y) => `${d} ${MONTHS[m]} ${y}`],
  [/^(\d+) (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)$/, (d, m) => `${d} ${MONTHS[m]}`],
  [/^(Mon|Tue|Wed|Thu|Fri|Sat|Sun) (\d+) (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)$/, (w, d, m) => `${DAYS[w]} ${d} ${MONTHS[m]}`],
  [/^(\d+):(\d+) (AM|PM)$/, (h, m, p) => `${h}:${m} ${partOfDay(Number(h) % 12 + (p === 'PM' ? 12 : 0))}`],
  [/^(\d+) visits?$/, (n) => `${n} معائنے`],
  [/^(\d+) years old$/, (n) => `عمر ${n} سال`],
  [/^(\d+) yrs$/, (n) => `${n} سال`],
  [/^BMI ([\d.]+) · (.+)$/, (b, label) => `بی ایم آئی ${b} · ${tr(label)}`],
  [/^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday),? (\d+) (January|February|March|April|May|June|July|August|September|October|November|December)( \d{4})?$/, (w, d, m, y) => `${tr(w)} ${d} ${LONG_MONTHS[m]}${y || ''}`],
  [/^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday) · (.+)$/, (w, rest) => `${tr(w)} · ${lookupTime(rest)}`],
  [/^(Mon|Tue|Wed|Thu|Fri|Sat|Sun) (\d+) (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec)$/, (w, d, m) => `${DAYS[w]} ${d} ${MONTHS[m.slice(0, 3)]}`],
  [/^(\d+) (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec) (\d{4}), (\d+:\d+)$/, (d, m, y, t) => `${d} ${MONTHS[m.slice(0, 3)]} ${y}، ${t}`],
  [/^Checked (\d+ \w+ \d{4}, \d+:\d+)$/, (d) => `جانچ: ${d}`],
];
