import { useEffect, useRef, useState } from 'react';
import { FiAlertTriangle, FiRefreshCw } from 'react-icons/fi';
import { streamAI } from '../lib/ai';
import Markdown from './Markdown';

// Runs one streamed AI generation (explain / summary) and renders it live
const AIStream = ({ path, run = true }) => {
  const [text, setText] = useState('');
  const [state, setState] = useState('idle'); // idle | streaming | done | error
  const [error, setError] = useState('');
  const [attempt, setAttempt] = useState(0);
  const abortRef = useRef(null);

  useEffect(() => {
    if (!run) return undefined;
    const controller = new AbortController();
    abortRef.current = controller;
    let acc = '';
    setText('');
    setError('');
    setState('streaming');
    streamAI(path, null, (ev) => {
      if (ev.type === 'text') {
        acc += ev.text;
        setText(acc);
      } else if (ev.type === 'error') {
        setError(ev.error);
        setState('error');
      } else if (ev.type === 'done') {
        setState('done');
      }
    }, controller.signal).catch((err) => {
      if (err.name !== 'AbortError') {
        setError('Connection lost.');
        setState('error');
      }
    });
    return () => controller.abort();
  }, [path, run, attempt]);

  return (
    <div className="ai-stream">
      {text && <Markdown text={text} />}
      {state === 'streaming' && !text && (
        <div className="stack gap-8">
          <div className="skeleton" style={{ height: 14, width: '70%' }} />
          <div className="skeleton" style={{ height: 14, width: '90%' }} />
          <div className="skeleton" style={{ height: 14, width: '55%' }} />
        </div>
      )}
      {state === 'streaming' && text && <span className="ai-caret" aria-hidden />}
      {state === 'error' && (
        <div className="asst-error" style={{ alignItems: 'center' }}>
          <FiAlertTriangle size={14} />
          <span className="grow">{error}</span>
          <button className="btn btn-ghost btn-sm" onClick={() => setAttempt((a) => a + 1)}><FiRefreshCw /> Retry</button>
        </div>
      )}
      {state === 'done' && (
        <p className="subtle" style={{ fontSize: 12, marginTop: 14 }}>Generated by AI from your PakMedRecord data. It can make mistakes — confirm anything important with a doctor.</p>
      )}
    </div>
  );
};

export default AIStream;
